<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DetalleEcaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * @return void
     */
    public function run()
    {
        DB::table('detalle_eca')->insert([
            [
                'id_detalle_eca' => 'DET-ECA-1',
                'telefonos' => '7757545148 ext. 111 Cel: 7775 133 4173',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 archivero.',
                'equipo_electr' => '1 cámara fotográfica, 1 cámara de video, 1 equipo de sonido, 1 impresora, 1 lap top, 1 computadora, 1 televisor de 43"',
                'material_didact' => '1 maqueta Contaminación de una Cuenca,  1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-1-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-2',
                'telefonos' => '7767629750 oficina 7761341136 personal',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:30 PM',
                'equipo_movil' => '1 Escritorio secretarial, 1 silla secretarial, 1 Archivero de 4 gavetas, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 monitor, 1 cámara fotográfica, 1 impresora multifuncional, 1 CPU, 2 laptop, 1 computadora de escritorio Slimline , 1 pantalla de 32" HISENSE,1 repro',
                'material_didact' => '1 maqueta Mantos Acuíferos, 1 maqueta Contaminación de una Cuenca, 1 maqueta reciclaje,1 relleno sanitario y agua limpia, 1 Cascos de Realidad virtual',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-2-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-3',
                'telefonos' => '7721811872',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 archivero, 1 escritorio secretarial, 1 silla secretarial,  1 pantalla para proyección con tripie, 1 toldo, 2 sillas, 1 mesa plegable.',
                'equipo_electr' => '1 computadora de escritorio, 1 impresora, 1 pantalla 32", 1 DVD, 1 CPU, 1 monitor, 1 mini laptop, 1 video proyector, 1 cámara fotográfica, 1 botarga i',
                'material_didact' => '1 maqueta Mantos Acuíferos, 1 maqueta Contaminación de una Cuenca,  1 maqueta Potabilización y Drenaje, 1 maqueta Ciclo del Agua,  1 super del agua, 1',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-3-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-4',
                'telefonos' => 'Tel: 7749741030 Cel: 771 332 5613',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 silla secretarial, 1 escritorio, 6 sillas plegables, 1 tablón mesa',
                'equipo_electr' => '1 laptop, 1 proyector, 1 pantalla 50"',
                'material_didact' => '1 maqueta Contaminación de una Cuenca, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-4-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-5',
                'telefonos' => '7731723650',
                'dias_hora_aten' => 'LUN-VIER 9:00 AM - 4:00 PM Y SABADO 9:00 AM - 2:00',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 1 silla plastico, 1 pizarron, 1 Mesa Plegable y 5 sillas Plegables',
                'equipo_electr' => '1 Televisor de 50", 1 Proyector y 1 LapTop, 1 equipo de sonido,1 DVD, 1 botarga',
                'material_didact' => '1 maqueta Mantos Acuíferos, 1 maqueta Contaminación de una Cuenca, 1 Cascos de Realidad virtual y 1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-5-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-6',
                'telefonos' => 'Tel: 7387288392  Cel: 7721183689',
                'dias_hora_aten' => 'LUN- VIERN 8:00 AM - 3:00 PM SAB 9:00 AM - 1:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretaria, 1 archiverol, 1 sillas blancas , 1 pizarron, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 cámara fotográfica, 1 equipo de sonido, 1 DVD, 1 pantalla de proyector, 1 equipo de perifoneo, 1 cámara de video, 1 computadora de escritorio, 1 pantalla de 32", 1 cámara fotográfica, 1 botarga',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminacion de una Cuenca, 1 Maqueta Potabilización y Drenaje y 1 Cascos de Realidad virtual y 1 Quiz del Agua',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-6-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-7',
                'telefonos' => 'Cel: 7751363861 7489121833',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 2 Archivero, 1 Pantalla de Proyeccion, 1 Toldo, 2 Sillas, 1 Mesa plegable, 1 Mesa Plegable y  5 sillas',
                'equipo_electr' => '1 proyector, 1 cámara fotografica, 1 computadora de escritorio, 1 impresora, 1 pantalla 32", 1 botarga, 1 bocina, 1 Televisor de 50", 1 Proyector y 1 LapTop',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca y 1 Cascos de Realidad virtual y 1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-7-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-8',
                'telefonos' => 'Tel: 7489127134 Cel: 7489127134',
                'dias_hora_aten' => 'LUN-VIER 9:00 AM - 4:30 SAB 9:00 A 1:00',
                'equipo_movil' => '1 silla secretarial, 1 escritorio secretarial, 2 archivero, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '2 proyector, 1 laptop, 1 equipo de sonido, 1 cámara de video, 1 pantalla de 32", 1 DVD computadora de escritorio, 2 cámara fotográfica, 1 CPU, 1 monitor, 1 impresora, 1 Pantalla de proyección, botarga, 1 Televisor de 50" y 1 LapTop',
                'material_didact' => '1 maqueta Mantos Acuíferos, 1 maqueta Contaminación de una Cuenca, 1 maqueta Ciclo del Agua 3D, 1 maqueta Potabilización y Drenaje, ,1 Cascos de Realidad virtual, y 1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-8-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-9',
                'telefonos' => '7721812746',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 1 archivero, 1 silla blanca de plastico, 1 pizarrón, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 Televisor de 50", 2 Proyector y 2 LapTop, 1 equipo de sonido, 1 cámara fotográfica, 1 impresora, 1 DVD, 1 pantalla de 32", 1 computadora de escritorio HP, Pantalla plegable para proyección y 1 botarga inflable',
                'material_didact' => 'Maqueta Contaminación de una Cuenca, maqueta Mantos Acuíferos, maqueta Ciclo del Agua, maqueta potabilización y drenaje,1 Casco de Realidad virtual y 1 Quiz del agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-9-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-10',
                'telefonos' => '7787373752 EXT 103 Y 107 Cel. 7717770855',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:30 PM - SAB 8:30',
                'equipo_movil' => '1 archivero con cuatro gavetas',
                'equipo_electr' => '2 televisiones, 1 computadora de escritorio, 2 cámaras fotografías, 2 laptops, 1 pantalla para proyección con tripie, 1 reproductor de DVD.',
                'material_didact' => '1 maqueta Mantos Acuíferos, 1 maqueta Contaminación de una Cuenca, 1 maqueta Ciclo del Agua 3D, 1 maqueta Potabilización y Drenaje, 1 maqueta de reciclaje, relleno sanitario y agua limpia, 1 súper del agua, 1 quiz del agua, 1 lentes de RV, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-10-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-11',
                'telefonos' => 'Tel: 7898944005 Cel: 7715267920',
                'dias_hora_aten' => 'LUN-VIER 9:00 AM - 04:00 PM',
                'equipo_movil' => '1 silla secretarial, 1 escritorio, 6 sillas plegables, 1 tablón mesa',
                'equipo_electr' => ' 1 laptop, 1 proyector, 1 pantalla 50"',
                'material_didact' => '1 maqueta Contaminación de una Cuenca, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-11-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-12',
                'telefonos' => '7711464295 Cel: 7711464295',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:30 PM',
                'equipo_movil' => '1 silla secretarial, 2 archivero, 1 escritorio secretarial, 15 silla blanca de plastico, 1 pizarron, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 proyector, 1 equipo de perifoneo, 1 equipo de sonido, 2 cámara fotografica,1 impresora, 1 computadora de escritorio, 1 pantalla de 32", 1 reproductor de DVD, 1 Televisor de 50", 2 Proyector y 1 LapTop',
                'material_didact' => '1 Maqueta Mantos Acuíferos , 1 Maqueta Contaminación de una Cuenca, 1 Maqueta ciclo del Agua,1 Cascos de Realidad virtual y 1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-12-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-13',
                'telefonos' => 'Tel: 7787351686 Cel: 778351686',
                'dias_hora_aten' => 'LUN-VIER 8:00 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 1 archivero, 1 silla blanca de plastico, 1 pizarron,  1 Pantalla para proyeccion con tripie, 1 Televisor de 50", 1 Proyector y 1 LapTop',
                'equipo_electr' => '1 laptop, 1 proyector, 1 equipo de perifoneo, 1 equipo de sonido, 1 impresora, 1 DVD, 1 computadora de escritorio, 2 cámara fotográfica, 1 video proyector, 1 pantalla de 32", 1 botarga',
                'material_didact' => '1 Maqueta Contaminación de una Cuenca, 1 Maqueta Mantos Acuíferos, 1 Maqueta Ciclo del Agua 3D,1 Maqueta Potabilización y Drenaje, 1 Cascos de Realidad virtual y 1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-13-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-14',
                'telefonos' => 'Cel: 7713575676',
                'dias_hora_aten' => 'LUN-VIER 9:00 AM - 04:00 PM',
                'equipo_movil' => '1 silla secretarial, escritorio secretarial, archivero',
                'equipo_electr' => '1 television, 1 videocasetera,1 CPU, 1 monitor, 2 laptop, 3 proyector, 1 equipo de perifoneo, equipo de sonido, 2 impresora, 1 computadora de escritorio, 1 cámara video, 2 cámara fotográfica, 1 pantalla 32"1 pantalla de proyección, 2 botargas',
                'material_didact' => '1 maqueta Contaminación de una Cuenca, 1 maqueta Mantos Acuíferos, 1 maqueta ciclo del Agua 3D,1 Maqueta Potabilización y Drenaje, 1 Cascos de Realidad virtual y 1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-14-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-15',
                'telefonos' => 'Tel: 7597270003 Cel: 7721543575',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 15 silla blanca de plastico, 1 pizarrón, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 televisión, 1 videocasetera, 1 proyector, 1 laptop, 1 impresora,1 computadora de escritorio,1 DVD, 1 pantalla 32", 1 cámara fotográfica.',
                'material_didact' => '1 maqueta Contaminación de una Cuenca, 1 maqueta de Relleno Sanitario,1 Cascos de Realidad virtual y 1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-15-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-16',
                'telefonos' => '7757703600',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:30 PM',
                'equipo_movil' => '1 silla secretarial,  1 escritorio secretarial, 1 archivero, 1 mesa Plegable y  5 sillas Plegable',
                'equipo_electr' => '1 cámara fotográfica, 1 pantalla de proyección, 1 laptop, 1 equipo de sonido,1 equipo de perifoneo, 1 impresora, 1 cámara de video, 1 computadora de escritorio, 1 DVD, 1 pantalla 32", 1 Televisor de 50", 2 Proyector y 1 LapTop',
                'material_didact' => 'Maqueta Contaminación de una Cuenca, maqueta Mantos Acuíferos,1 Cascos de Realidad virtual y 1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-16-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-17',
                'telefonos' => 'Tel: 7637285034 Cel: 7731309111',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 silla secretarial, 1 archivero, 1 escritorio secretarial, 15 silla blanca de plastico, 1 pizarron, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 equipo de sonido, 1 laptop, 1 cámara fotográfica, 1 DVD, 1 pantalla 32", 1 impresora, 1 computadora de escritorio, 1 Televisor de 50", 1 Proyector y 1 LapTop',
                'material_didact' => '1 maqueta Contaminación de una Cuenca, 1 maqueta Mantos Acuíferos,,1 Cascos de Realidad virtual, 1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-17-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-18',
                'telefonos' => 'Tel: 4833782056 Cel: 7713519386',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 1 archivero, 15 silla blanca de plastico, 1 pizarrón, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 equipo de sonido, 1 impresora, 1 Televisor de 50", 1 Proyector y 1 LapTop',
                'material_didact' => '1 maqueta Contaminación de una Cuenca, ,1 Cascos de Realidad virtual, 1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-18-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-19',
                'telefonos' => '7387830143 Cel. 7721238594',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 1 archivero, 15 sillas blancas de plástico, 1 pizarrón, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '2 cámara fotográfica, 1 laptop, 1 equipo de sonido, 1 computadora de escritorio, 1 cámara de video, 1 pantalla 32", 1 Televisor de 50", 1 Proyector y 1 LapTop',
                'material_didact' => '1 maqueta Contaminación de una Cuenca, maqueta Mantos Acuíferos,1 Cascos de Realidad virtual, 1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-19-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-20',
                'telefonos' => 'Tel: 7296950434',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:30 PM',
                'equipo_movil' => '1 silla secretarial, 1 escritorio, 6 sillas plegables, 1 tablón mesa',
                'equipo_electr' => '1 proyector, 1 laptop,1 pantalla de proyección, 1 computadora de escritorio, 1 botarga, 1 pantalla de 50"',
                'material_didact' => '1 maqueta Contaminación de una Cuenca, 1 maqueta mantos acuíferos, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-20-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-21',
                'telefonos' => 'Tel. 7491044766',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:30 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 15 silla blanca de plastico, 1 pizarron, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '2 laptop, 1 impresora, 1 cámara fotográfica,  2 proyector, 1 equipo de sonido, 1 Televisor de 50"',
                'material_didact' => '1 Casco de Realidad virtual, 1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-21-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-22',
                'telefonos' => 'Tel: 79 25059 ext 122 Cel: 7713034880',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 silla secretarial, 1 escritorio, 6 sillas plegables, 1 tablón mesa',
                'equipo_electr' => '1 laptop, 1 proyector,1 Televisor de 50"',
                'material_didact' => '1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-22-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-23',
                'telefonos' => '7387240112 EXT. 111 7721512777',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial,1 archivero, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 equipo de sonido,1 computadora de escritorio, 1 pantalla de 32", 2 cámara fotográfica, 1 DVD, 1 CPU,1 monitor, 2 laptop 1 Televisor de 50", 1 Proyector',
                'material_didact' => '1 Maqueta Contaminación de una Cuenca, 1 Maqueta Mantos Acuíferos, 1 Casco de Realidad virtual, 1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-23-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-24',
                'telefonos' => '7387241190 Cel: 7712021065',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 silla secretarial, 1 escritorio secretarial,1 archivero, 1 Pantalla de proyeccion, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 equipo de sonido, 1 equipo de perifoneo, 2 laptop, 2 cámara fotográfica, 2 proyector, 1 impresora, 1 cámara de video, 1 pantalla 32"1 DVD, 1 computadora de escritorio, 1 pantalla de 32", 1 Botarga.',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca, 1 Maqueta Potabilización y Drenaje, 1 Maqueta Ciclo del Agua 3D , 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-23-1-2'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-25',
                'telefonos' => 'Tel: 771 7920101, 771 7920253 CEL: 7711256204',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:30 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial,1 archivero, 14 silla blanca de plastico, 1 pizarron',
                'equipo_electr' => ' 1 laptop, 1 proyector, 1 pantalla de proyección, equipo de perifoneo,1 equipo de sonido1 ,DVD, 1 cámara fotográfica, 1 computadora de escritorio, 1 impresora, 1 pantalla 32", 1 Botarga, computadora portatil',
                'material_didact' => '1 Maqueta Contaminación de una Cuenca, 1 Maqueta Mantos Acuíferos, 1 Maqueta de reciclaje, 1 Relleno Sanitario y Agua Limpia,  1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-24-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-26',
                'telefonos' => 'Cel: 7716289264',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 14 silla blanca de plastico, 1 pizarron, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 equipo de sonido, 1 computadora de escritorio,  1 DVD, 1 Televisor de 50", 1 Proyector y 2 LapTop',
                'material_didact' => '1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-25-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-27',
                'telefonos' => 'Cel: ',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '2 escritorios secretariales, 2 sillas secretariales, 1 mesa tablón, 6 sillas plegables',
                'equipo_electr' => ' 1 impresora, 1 cámara fotográfica, 1 proyector, 1 laptop, 1 pantalla 50"',
                'material_didact' => '1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-26-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-28',
                'telefonos' => '7747437296 Cel: 7711903115',
                'dias_hora_aten' => 'DOM - VIER 8:00 AM - 03:00 PM',
                'equipo_movil' => '1 silla secretarial, 1 escritorio, 6 sillas plegables, 1 tablón mesa',
                'equipo_electr' => ' 1 laptop, 1 proyector, 1 pantalla 50"',
                'material_didact' => '1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-27-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-29',
                'telefonos' => '(045) 7712008381 01 (789) 8965621 Ext. 106 Cel: 7713550085',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM - SAB 8:00 - 12:00',
                'equipo_movil' => '1 escritorio secretarial,  silla secretarial, 1 archivero, 1 silla blanca de plastico, 1 pizarron, 1 pantalla para proyeccion con tripie,',
                'equipo_electr' => '1 televisión, 1 videocasetera, 1 CPU,1 monitor, 2 proyector, 2 laptop, equipo de sonido, 2 cámara fotografica,1 impresora, 1 equipo de perifoneo, 1 DVD, 1 pantalla 32",1 computadora de escritorio, 1 cámara de video, televisor de 43"',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca, 1 Maqueta Ciclo del Agua 3D, 1 Maqueta Potabilización y Drenaje,  1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-28-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-30',
                'telefonos' => 'Tel: 7898550001 Cel: 7713653610',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 06:00 PM',
                'equipo_movil' => '1 Archivero, 2 Escritorios Secretariales, 2 Sillas Secretariales, 1 Toldo, 8 Sillas plegables, 2 Mesas plegables.',
                'equipo_electr' => '1 Computadora de Escritorio, 1 Impresora Multifuncional, 1 Reproductor de DVD, 1 Pantalla de 32", 2 Proyectores, 1 Cámara Fotográfica, 1 Bocina, 1 pantalla de 50", 1 laptop',
                'material_didact' => '1 Maqueta de Mantos Acuíferos, 1 Maqueta de reciclaje, relleno sanitario y Agua Limpia, loterías, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-28-1-4'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-31',
                'telefonos' => 'Oficina: 7617822590 ext 105 Cel: 7731333924',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, archivero, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '2 proyector, 1 equipo perifoneo, 1 equipo de sonido, 1 impresora, 1 pantalla 32", 2 laptop, computadora de escritorio, 1 cámara fotografica,1 cámara de video, 1 Pantalla de 32", 1 Pantalla de Proyección, 1 Botarga, 1 Televisor de 50" y 1 LapTop',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-29-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-32',
                'telefonos' => '7731557507',
                'dias_hora_aten' => 'LUN-VIER 9:00 AM - 06:00 PM',
                'equipo_movil' => '2 archivero, 1 silla secretarial, 1 escritorio secretarial, 15 silla blanca de plastico,1  pizarron, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '2 laptop, 2 cámara fotográfica, 1 proyector, 1 impresora, 1 laptop, 1 DVD,1 pantalla 32", 1 Pantalla de Proyección, 1 Botarga, 1 Televisor de 50", 2 Proyector y 2 LapTop, 1 Televisor de 50"',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca, 1 Maqueta de Relleno Sanitario, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-29-1-2'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-33',
                'telefonos' => 'Tel: 7597238689 7597288157 Cel: 7712434482',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 archivero, 1 silla secretarial, 14 silla blanca de plastico, 1 pizarron, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => 'equipo de sonido, 2 proyector, 1 cámara de video, 1 computadora de escritorio, 1 impresora,1 DVD, 1 cámara fotográfica, 2 laptop, 1 pantalla de proyección, 1 Kiosko, 1 pantalla 32", 1 Televisor de 50"',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca, 1 Maqueta Ciclo del Agua 3D, 1 Maqueta Potabilización y Drenaje, 1 Casco de Realidad virtual,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-30-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-34',
                'telefonos' => 'Tel: 4412933197 Cel: 7713426446',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 1 archivero, 15 silla blanca de plastico, 1  pizarron',
                'equipo_electr' => '1 Laptop, 1 equipo de perifoneo,1 equipo de sonido,1 impresora, 1 cámara fotográfica, 1 pantalla 32", 1 DVD, 1 Computadora de escritorio, 1 Pantalla de Proyección, 1 Pantalla de 32", 1 Botarga, 1 Televisor de 50", 2 Proyector y 2 LapTop',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca,1 Maqueta Potabilización y Drenaje, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-31-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-35',
                'telefonos' => '7712360590',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 15 silla blanca de plastico, 1 pizarron, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => ' 1 equipo de sonido, 1 impresora, 1 DVD, 2 cámara fotográfica, 1 Televisor de 50", 2 Proyector y 1 LapTop',
                'material_didact' => '1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-32-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-36',
                'telefonos' => 'Cel: 553954780 Tel:  7711919586',
                'dias_hora_aten' => 'LUN-VIER 9:00 AM - 05:00 PM',
                'equipo_movil' => '1 silla secretarial, 1 escritorio, 6 sillas plegables, 1 tablón mesa',
                'equipo_electr' => ' 1 laptop, 1 proyector, 1 pantalla 50"',
                'material_didact' => '1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-33-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-37',
                'telefonos' => 'Cel: 7714032168 7713504431',
                'dias_hora_aten' => 'LUN-VIER 9:00 AM - 05:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 laptop, 2 Video proyector, 1 Pantalla de 32", 1 pantalla de 50"',
                'material_didact' => '1 Maqueta Contaminación de una Cuenca, 1 Maqueta ciclo del Agua, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-34-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-38',
                'telefonos' => 'Cel: Miguel Asian Barona',
                'dias_hora_aten' => 'LUN-VIER 9:00 AM - 05:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 laptop, 1 proyector,1 computadora de escritorio, 1 pantalla 32", 1 DVD, 1 pantalla de 50"',
                'material_didact' => '1 Maqueta Contaminación de una Cuenca, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-35-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-39',
                'telefonos' => '7711173467',
                'dias_hora_aten' => 'LUN-VIE 8:30 AM - 04:30 PM',
                'equipo_movil' => '1 Escritorio Secretaria, 1 Silla Secretarial, 1 pizarron, 1 Archivero de 4 Gavetas, 1 Toldo,2 Mesa Plegable y  7 sillas Plegables',
                'equipo_electr' => ' 1 Cámara Fotográfica, 1 Laptop, Equipo de Sonido, 1 Cámara de Video, DVD, 1 Impresora, 1 Computadora de Escritorio, 1 Bocina, 1 Televisor de 50", 1 Proyector y 1 LapTop',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-36-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-40',
                'telefonos' => '7747430841 ext-11 Cel. 7712049344',
                'dias_hora_aten' => 'LUN-VIER 9:00 AM - 05:00 PM',
                'equipo_movil' => '1 Archivero, 25 Sillas Blancas de Plástico, 1 Pizarrón. ',
                'equipo_electr' => '1 Laptop, 2 Cámara Fotográfica, 1 equipo de sonido, 1 impresora, 1 Televisión, 1 videocasetera,1 equipo de perifoneo, 1 Cámara fotografica,1 proyector.',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca, 1 Maqueta Potabilización y Drenaje, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-37-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-41',
                'telefonos' => 'Cel: 7711099802 Tel: 7717153511 ext 114',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 Escritorio Secretarial, 1 Silla Secretarial, 25 Sillas Blancas de plasticos, 1 pizarrón, 1 Mesa Plegable y  5 sillas Plegables  ',
                'equipo_electr' => ' 1 Cámara Fotográfica, 1 Impresora, 1 Computadora de Escritorio, 1 DVD, 1 Televisor de 50", 2 Proyector y 2 LapTop ',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-38-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-42',
                'telefonos' => 'Tel: 7717971216 Ext 118 Dirección de Ecología',
                'dias_hora_aten' => 'LUN-SAB 8:30 - 04:00',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 laptop, 1 proyector, 1 pantalla 32", 1 pantalla de 50".',
                'material_didact' => '1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-39-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-43',
                'telefonos' => '7745984040 Cel. 7712002049',
                'dias_hora_aten' => 'LUN-VIER 9:00 AM - 04:00 PM',
                'equipo_movil' => '2 escritorios secretariales, 2 sillas secretariales, 1 archivero, 1 mesa tablón, 6 sillas plegables',
                'equipo_electr' => '1 laptop,  1 computadora de escritorio, 1 impresora multifuncional, 1 pantalla 32",  1 pantalla de 50", 1 proyector',
                'material_didact' => '1 maqueta mantos acuíferos, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-40-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-44',
                'telefonos' => 'Tel: 7387350574 Cel:7721322389',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial,1  silla secretarial, 1 archivero, 25 silla blanca de plastico, 1 pizarron, 1 pantalla para proyeccion con tripie,',
                'equipo_electr' => '1 proyector, 1 camara de video, 1 pantalla 32", 1 DVD, 1 impresora,1 camara fotografica, 1 Computadora de Escritorio, 1 Pantalla de 32", 1  Botarga inflable, computadora portatil',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca, 1 Maqueta Potabilización y Drenaje,  1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-41-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-45',
                'telefonos' => 'Tel: 774 7450002 Cel: 7713234581',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 laptop, 1 proyector, 1 pantalla 32", 1 pantalla de 50".',
                'material_didact' => '1 maqueta Contaminación de una Cuenca, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-42-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-46',
                'telefonos' => '7595963211',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 laptop, 1 proyector, 1 pantalla 32", 1 pantalla de 50".',
                'material_didact' => '1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-43-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-47',
                'telefonos' => '7617821308 7731339206',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 25 silla blanca de plastico,1  pizarron,1  pantalla para proyeccion tripie apoyo, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => ' 1 computadora de escritorio, 1 DVD, 1 pantalla 32", 1 camara de video, 1 impresora, 2 camara fotografica, 1  equipo de sonido, 1 Televisor de 50", 2 Proyector y 2 LapTop',
                'material_didact' => '1 Maqueta Mantos Acuíferos,1 Maqueta Contaminación de una Cuenca, 1 Maqueta Potabilización y Drenaje, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-44-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-48',
                'telefonos' => '7712029631',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 1 archivero, 25 sillas blancas de plástico, 1 pizarrón, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => ' 2 proyectores, 2 laptops, 1 equipo de perifoneo, 1 cámara de video, 2 cámaras fotograficas,1 equipo de sonido,1 DVD, 1 computadora de escritorio, 1 impresora, 1 Pantalla de 32", 1 botarga, 1 Televisor de 50", 1 Proyector',
                'material_didact' => '1 maqueta Contaminación de una Cuenca, 1 maqueta ciclo del Agua, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-45-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-49',
                'telefonos' => 'Cel: 771 121 4790',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 Escritorio Secretarial, 1 Silla Secretarial, 1 Archivero,  1 mesa tablón, 6 sillas plegables',
                'equipo_electr' => '1 Laptop, 1 Proyector, 1 Computadora de Escritorio, 1  DVD, 1 Impresora Multifuncional, 1 Pantalla de 32", 1 pantalla de 50"',
                'material_didact' => '1 Maqueta de reciclaje, relleno sanitario y agua limpia, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-46-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-50',
                'telefonos' => 'Cel: 5545775687',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 silla secretarial, 1 escritorio secretarial, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => 'television, 1 cámara fotográfica, 1 laptop, 1 impresora, 1 Televisor de 50", 1 Proyector y 1 LapTop',
                'material_didact' => '1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-47-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-51',
                'telefonos' => '7717174300',
                'dias_hora_aten' => 'LUN-SAB 8:30 - 04:00',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 1 Toldo, 2 Mesa Plegable y  7 sillas Plegables',
                'equipo_electr' => '2  Laptop, 3 Proyector, 1 Equipo de Sonido, 1 pantalla de 32, impresora, 1 computadora de escritorio, 1  Bocina, 1 Kiosko, 1 Televisor de 50"',
                'material_didact' => '1 Maqueta Contaminación de una Cuenca, 1 Maqueta Ciclo del Agua 3D, 1 Maqueta Potabilización y Drenaje, 1 Maqueta de reciclaje, relleno sanitario y agua limpia, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-48-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-52',
                'telefonos' => '7717172850 ext 2101 y 2102',
                'dias_hora_aten' => 'LUN - VIE 9:00 - 15:00',
                'equipo_movil' => '1 silla secretarial, 1 escritorio secretarial, 35 sillas de plastico,1  pizarron, 1 stand, 1 archivero, 1 Toldo, 2 Sillas plegables, 1 Mesa plegable',
                'equipo_electr' => '1 televisión, 1 impresora, 1 pantalla de proyección, 3 computadora de escritorio, 3 proyector, 3 cámara fotográfica, 1 cámara de video, 1 DVD, 1 equipo de sonido, 1 pantalla 32", 1 DVD, 1 impresora,1 cámara de video, 1 cámara profesional,1 Botarga, 2 Cascos para video 360°, 2 Smartphone, 1 Pantalla de 32", Bocina, 1 Kiosko, pantalla inflable con laptop(tripode), bocina(microfonos), proyector, computadora portatil y televisor de 43"',
                'material_didact' => '1 Maqueta Contaminación de una Cuenca, 1 Maqueta Mantos Acuíferos, 1 Maqueta Potabilización y Drenaje,1 Maqueta Ciclo del Agua 3D, 1 Maqueta de reciclaje, relleno sanitario y agua limpia, 1 domo inflable, 1 juego interactivo software (¿Cuánto sabes sobre el agua?) y 1 quiz del agua,  2 super del agua, 1  placa de identificación, 1 sistema de proyección fulldome',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-48-1-3'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-53',
                'telefonos' => '5551859158',
                'dias_hora_aten' => 'LUN - VIE 8:30 - 16:30',
                'equipo_movil' => ' 1 Pantalla de Proyeccion, 2 Sillas plegables, 1 Mesa plegable',
                'equipo_electr' => '1 computadora de escritorio, 2 proyector, 1 DVD, 2 Cascos para video 360 con smarphone, 10 cascos para video 360,  3domo planetario y 2 software (¿Cuánto sabes sobre el agua?)  pantalla inflable con laptop(tripode), bocina(microfonos), 1 computadora portatil y televisor de 43"',
                'material_didact' => 'Maqueta Contaminación de una Cuenca, Maqueta Mantos Acuíferos, Maqueta Potabilización y Drenaje, Maqueta Ciclo del Agua 3D, Maqueta de reciclaje, relleno sanitario y agua limpia,  3 domo inflable, 2 juego interactivo software (¿Cuánto sabes sobre el agua?), 2 quiz del agua, 12 Cascos para video 360°y pantalla inflable con laptop(tripode), 2 súper del agua, 1  placa de identificación, 1 sistema de proyección fulldome',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-48-1-4'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-54',
                'telefonos' => '7711868093',
                'dias_hora_aten' => 'LUN - VIE 8:00 - 15:30',
                'equipo_movil' => '1 escritorio secretarial,1  silla secretarial, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 Televisor de 50", 1 Proyector y 1 LapTop',
                'material_didact' => '1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-48-1-6'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-55',
                'telefonos' => 'Cel: 7711864247',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 laptop, 1 proyector, 1 pantalla 32", 1 pantalla de 50".',
                'material_didact' => '1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-49-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-56',
                'telefonos' => '7387250950',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 Escritorio Secretaria, 1 Silla Secretarial, 25 silla blanca de plastico, 1 pizarron,1  Archivero con 4 gavetas,  Pantalla para proyeccion con tripie , 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => ' 1 camara fotografica,1  Computadora de Escritorio, 1  Cámara de Video,  1 DVD,2  Impresora, 1 Pantalla de 32", 1 Botarga, computadora portatil, 1 Televisor de 50", 2 Proyector y 1 LapTop',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca,  1 súper del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-50-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-57',
                'telefonos' => '7716571914',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 1 archivero, 25 silla blanca de plastico, 1 pizarron, 1 Mesa Plegable y  5 sillas Plegables ',
                'equipo_electr' => ' 1 computadora de escritorio,1  impresora, 1 camara fotografica,1  Pantalla de 32", 1 Pantalla de Proyeccion, 1  Botarga, 1 Televisor de 50", 2 Proyector y 2 LapTop ',
                'material_didact' => 'Maqueta Mantos Acuíferos, Maqueta Contaminación de una Cuenca, Maqueta Potabilización y Drenaje, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-51-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-58',
                'telefonos' => '7731441087',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 Escritorio Secretarial, 1 Silla Secretarial,1  silla blanca de plastico, 1 pizarron, 1 Archivero de 4 gavetas,1 Pantalla para proyeccion con tripie, ',
                'equipo_electr' => '1 Equipo de Sonido, 1 Cámara Fotográfica, 1 Computadora de Escritorio, 1 DVD, 1 Impresora,1 Equipo de Sonido,1 Equipo de Perifoneo, 1 Mini Laptop, 1 Pantalla de 32" , 1 Televisor de 50", 2 Proyector y 1 LapTop',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca, 1 Maqueta Ciclo del Agua 3D, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-52-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-59',
                'telefonos' => '5623263042',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 Escritorio secretarial, 1  Silla Secretarial , 25 silla blanca de plastico,1  pizarron',
                'equipo_electr' => '1 DVD,1  Impresora, 1 Cámara Fotográfica, Televisor de 43", computadora portatil',
                'material_didact' => '1 Maqueta de reciclaje, relleno sanitario y agua limpia, 1 súper del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-53-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-60',
                'telefonos' => '7727282000',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => 'Escritorio Secretarial, Silla secretarial, Toldo, 2 Mesa Plegable y  7 sillas Plegables ',
                'equipo_electr' => ' 2  Cámara Fotográfica,1 minilap, 1 Computadora de Escritorio, 1  Impresora, 1  Equipo de Sonido, 1 Videoproyector, 1 Pantalla de 23",  Reproductor de DVD, 1 Bocina, 1 Televisor de 50", 2 Proyector y 1 LapTop',
                'material_didact' => '1 Maqueta Mantos Acuíferos, Maqueta Contaminación de una Cuenca, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-54-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-61',
                'telefonos' => '7721587836',
                'dias_hora_aten' => 'LUN-VIER 8:00 AM - 04:00 PM',
                'equipo_movil' => 'Escritorio secretaria, silla secretarial, pizarrón,  30 sillas de plástico, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 cámara fotográfica, 1 DVD, 1 computadora de escritorio, 1 impresora multifuncional, 1 equipo de sonido, 1 Televisor de 50", 1 Proyector y 1 LapTop',
                'material_didact' => '1 maqueta Mantos Acuíferos, 1 maqueta Contaminación de una Cuenca, 1 maqueta Potabilización y Drenaje, 1 maqueta de Relleno Sanitario, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-54-23-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-62',
                'telefonos' => '7714142914',
                'dias_hora_aten' => 'LUN-VIER 8:00 AM - 04:00 PM',
                'equipo_movil' => '1 Escritorio Secretaria, 1 Silla Secretarial, 1 Archivero ',
                'equipo_electr' => '1  Equipo de Sonido,1  DVD, 1  Videocasetera, 1 Television, Botarga, cmputadora portatil.',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca, 1 Maqueta de reciclaje, relleno sanitario y agua limpia, 1 súper del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-55-1-2'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-63',
                'telefonos' => 'Cel: 7751295596',
                'dias_hora_aten' => 'LUN-SAB 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretaria, 1 silla secretarial, 1 archivero 1 toldo, 2 sillas, 1 mesa plegable',
                'equipo_electr' => ' 1 proyector, 1 cámara fotográfica, 1 cámara de video, 1 equipo de perifoneo, 1 equipo de sonido,  1 computadora de escritorio, 1 impresora, 1 pantalla de 32", 1 DVD, 1 bocina, computadora portatil',
                'material_didact' => '1 maqueta Mantos Acuíferos, 1 maqueta de reciclaje, relleno sanitario y agua limpia, 1 súper del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-56-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-64',
                'telefonos' => 'Cel: 7713412769',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 laptop, 1 proyector, 1 pantalla 32", 1 pantalla de 50".',
                'material_didact' => '1 maqueta Mantos Acuíferos, 1 maqueta Contaminación de una Cuenca, 1 maqueta Potabilización y Drenaje, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-57-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-65',
                'telefonos' => 'Tel: 7597235043 Ext. 111 Cel: 7721117063',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 laptop, 1 proyector, 1 pantalla 32", 1 pantalla de 50".',
                'material_didact' => '1 Maqueta Contaminación de una Cuenca, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-58-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-66',
                'telefonos' => '5535704624',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretaria , 1 silla secretarial, 1 pantalla de proyección, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 cámara fotográfica, 2 laptop,1 equipo de sonido, 1 impresora, 1 equipo de perifoneo, 1 computadora de escritorio, 1 pantalla de 32", 1 cámara fotográfica, 1 botarga, 1 Televisor de 50", 1 Proyector',
                'material_didact' => '1 maqueta Mantos Acuíferos,1 maqueta Contaminación de una Cuenca, 1 maqueta de relleno Sanitario, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-59-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-67',
                'telefonos' => 'Tel: 7751031518',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 laptop, 1 proyector, 1 pantalla 32", 1 pantalla de 50".',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-60-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-68',
                'telefonos' => 'Tel:7919130612 ext 114 Cel: 7714446732',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 laptop, 1 proyector, 1 pantalla 32", 1 pantalla de 50".',
                'material_didact' => '1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-61-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-69',
                'telefonos' => '7747427029',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretaria, 1 silla secretarial, 1 Mesa Plegable y  5 sillas Plegables ',
                'equipo_electr' => '1 equipo de sonido, 1 DVD, impresora, 1 cámara fotográfica, 1 Televisor de 50", 1 Proyector y 1 LapTop',
                'material_didact' => '1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-62-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-70',
                'telefonos' => '017737330058 Cel: 7731074705',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => 'Escritorio Secretaria,  Silla Secretarial, Pantalla de Proyeccion,',
                'equipo_electr' => ' 1 Camara de Video, 2  Laptop, 1 Proyector, 2 Cámara Fotográfica, 1 Equipo de Sonido,1  Impresora, 1 DVD, 1 Pantalla de 32, 1 Computadora de Escritorio, 1 , Botarga, computadora portatil',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca, 1 Maqueta Potabilización y Drenaje, 1 Ciclo del Agua en 3D, 1 súper del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-63-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA0-71',
                'telefonos' => 'Cel:7731050856',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 Escritorio Secretaria, 1 Silla Secretarial, 25 silla blanca de plastico,1 pizarron, 1 Archivero, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 Televisor de 50", 1 Proyector y 1 LapTop, 1 cámara fotográfica, 1 Equipo de sonido,1  impresora y 1 DVD',
                'material_didact' => '1 Maqueta Ciclo del Agua 3D, 1 Maqueta Potabilización y Drenaje, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-64-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-72',
                'telefonos' => '7787824043',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretaria,  1 silla secretarial, archivero,  25 silla blanca de plastico, 1 pizarrón, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '2  laptop, 2 proyectores, 1 equipo de perifoneo, 1 equipo de sonido, 1 impresora, 1 cámara de video, 1 cámara fotográfica, 1 pantalla 33, 1 botarga, 1 Televisor de 50"',
                'material_didact' => '1 maqueta Mantos Acuíferos, 1maqueta Contaminación de una Cuenca, 1 maqueta Potabilización y Drenaje, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-65-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-73',
                'telefonos' => '7751575175',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 Escritorio Secretaria, 1 Silla Secretarial, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => ' 1 Equipo de Sonido,  1 Cámara Fotográfica,1  Impresora, 1 Camara de Video,1  DVD,1  Pantalla de 33, 1 Botarga, 1 Televisor de 50", 1 Proyector y 2 LapTop',
                'material_didact' => '1 Maqueta Mantos Acuíferos,1 Maqueta Contaminación de una Cuenca , 1 Maqueta Potabilización y Drenaje, 1 Maqueta ciclo del agua, 1 Maqueta de relleno Sanitario, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-66-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-74',
                'telefonos' => 'TEL. OFICINA(Dirección): 7731047586 CEL: 7731798516',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 Escritorio Secretaria Silla, 1 Secretarial, 1 Archivero , 1 Pantalla para proyeccion con tripie , 1 Toldo, 7 Sillas, 2 Mesa plegable',
                'equipo_electr' => '2  Laptop,  1 Equipo de Sonido, 2 Proyector, 1 Equipo de Perifoneo,1  Camara de Video, 1 Computadora de escritorio,1  DVD , 1 Videoproyector, 1 Pantallde 32",1  Bocina, 1 Televisor de 50"',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-67-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-75',
                'telefonos' => 'Cel: 7713523127',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 laptop, 1 proyector, 1 pantalla 32", 1 pantalla de 50".',
                'material_didact' => '1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-68-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-76',
                'telefonos' => 'Tel: 7797964635 7797967993 7791007583 Cel:5514592944',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio, 1 secretaria silla, 1 secretarial, 1 archivero, 1 pantalla para proyección con tripie, 1 toldo, 2 sillas, 1 mesa plegable',
                'equipo_electr' => ' 3 cámaras fotograficas, 1 laptop, proyector, 1 pantalla de proyección, 1 cámara de video, 1 equipo de perifoneo, 1 equipo de sonido, 1 impresora,  1 DVD, 1  pantalla de 32, 1 computadora de escritorio, 1 videoproyector, 1 botarga, 1 bocina, 1 Kiosko, computadora portatil',
                'material_didact' => '1 maqueta Mantos Acuíferos, 1 maqueta Contaminación de una Cuenca, 1 maqueta Ciclo del Agua 3D, 1 maqueta potabilización y drenaje, 1 súper del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-69-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-77',
                'telefonos' => '7637860578 CEL. 773 158 6649',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 Escritorio Secretaria, 1 Silla Secretarial, 1 Archivero Pantalla de proyeccion, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '2 Laptop, 1 Cámara Fotográfica, 2 Proyector,1  Equipo de Sonido,1  Impresora, 1 DVD, 1 Computadora de escritorio,1  Botarga, 1 Televisor de 50"',
                'material_didact' => '1 Maqueta Mantos Acuíferos,1 Maqueta Contaminación de una Cuenca, 1 maqueta potabilización y drenaje, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-70-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-78',
                'telefonos' => 'Cel: 7711543497',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretaria,  1 silla secretarial, 1 Mesa Plegable y  5 sillas Plegables ',
                'equipo_electr' => '2 laptop, 2  proyector, 1 cámara fotográfica, 1 equipo de sonido, 1 DVD, 1 impresora, 1 Televisor de 50"',
                'material_didact' => '1 maqueta Mantos Acuíferos, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-71-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-79',
                'telefonos' => '7919131153 EXT 105 Cel: 7751234365',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 Pantalla de Proyeccion, 1 Escritorio Secretarial, 1 silla secretarial, 1 mesa tablón, 6 sillas plegables',
                'equipo_electr' => '1 Televisión, 1 Computadora de Escritorio, 1 Botarga, 1 Proyector, 1 laptop, 1 Pantalla de 50" ',
                'material_didact' => '1 Maqueta Contaminación de una Cuenca, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-72-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-80',
                'telefonos' => 'Presidencia: 7749740018 Llamadas: 7715567367 WhatsApp: 7712217508',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 Botarga, 1 Proyector, 1 laptop, 1 Pantalla de 50"',
                'material_didact' => '1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-73-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-81',
                'telefonos' => '55 3570 2744',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial, 1 silla secretarial, 1 archivero, 1 pantalla para proyeccion con tripie, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1  equipo de sonido,1  cámara fotográfica, 1 pantalla 32, 1  impresora, 1 DVD, 1  computadora de escritorio, 2 videoproyector, 1 botarga, 1 Televisor de 50", 1 LapTop',
                'material_didact' => '1 maqueta Mantos Acuíferos, 1 maqueta Contaminación de una Cuenca, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-74-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-82',
                'telefonos' => '7437410977',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables.',
                'equipo_electr' => '1 laptop, 1 proyector, 1 Impresora,1  DVD, 1 Pantalla de 50"',
                'material_didact' => '1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-75-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-83',
                'telefonos' => '017737325003 EXT 111 CEL: 7731264305',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 Escritorio Secretaria,1 Silla Secretarial, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 Televisor de 50", 1 Proyector y 1 LapTop',
                'material_didact' => ' 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-76-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-84',
                'telefonos' => 'Tel: 7757538422 ext 1182 Cel. 5564662038',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretaria, 1 silla secretarial, 1 archivero de 4 gavetas, 1 pantalla para proyeccion con tripie, 1 toldo, 7 sillas, 2 mesa plegable',
                'equipo_electr' => '1 camara de video, 2  laptop, 2 cámara fotográfica,  3 proyector,  1 impresora,  1 equipo de sonido,  1 pantalla de 32" , 1 computadora de esritorio,1  DVD, 1 botarga, 1 bocina, 1 Televisor de 50"',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 maqueta Ciclo del Agua 3D, 1 maqueta Potabilización y Drenaje, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-77-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-85',
                'telefonos' => '7751449476',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 Archivero, 1 escritorio secretarial, 1 silla secretarial, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 computadora de escritorio, 1 pantalla de 32", 1 cámara fotográfica, 2 computadora portatil, 1 Televisor de 50", 1 Proyector',
                'material_didact' => '1 maqueta de relleno sanitario, 1 súper del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-77-1-5'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-86',
                'telefonos' => '775 112 2940',
                'dias_hora_aten' => 'LUN-VIER 9:00 AM - 06:00 PM',
                'equipo_movil' => '35 Sillas de Plastico , 1 Escritorio Secretarial, 1 Silla Secretarial,1  Pizarron,1  Pantalla de Proyeccion, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => '1 Proyector, 1 Laptop, 1 Proyector, 2 Cámara Fotográfica,1  Impresora,1   Equipo de Sonido,1  Pantalla 32, 1 DVD, 1 Pantalla de 32", 1 botarga, 1 Mesa Plegable y  5 sillas Plegables',
                'material_didact' => '1 Maqueta Mantos Acuíferos, Maqueta Contaminación de una Cuenca, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua,1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-77-1-3'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-87',
                'telefonos' => 'Cel: 8137060865 CEL. LLAMADAS 7296828476 WHATS: 7713225379',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 laptop, 1 proyector, 1 Pantalla de 50"',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-78-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-88',
                'telefonos' => '7711415494',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 Escritorio Secretaria, 1   Silla Secretarial    Archivero, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => ' 2 Laptop, 1 Equipo de Sonido, 1 Cámara Fotográfica, 1 DVD, 1 Televisor de 50", 1 Proyector',
                'material_didact' => '1 Maqueta Contaminación de una Cuenca, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-79-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-89',
                'telefonos' => 'Cel: 7717204860',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 laptop, 1 proyector, 1 Pantalla de 50"',
                'material_didact' => '1 maqueta ciclo del agua, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-80-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-90',
                'telefonos' => '7747420022',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 Escritorio Secretarial,   1 Silla Secretarial,  1 Archivero, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => ' 1 Cámara de Video, 1 Televisor de 50", 1 Proyector y 1 LapTop',
                'material_didact' => '1 Maqueta Mantos Acuíferos, 1 Maqueta Contaminación de una Cuenca, 1 Maqueta de Relleno Sanitario, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-81-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-91',
                'telefonos' => 'Cel: 7716833246',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables.',
                'equipo_electr' => '1 laptop, 1 proyector, 1 Pantalla de 50"',
                'material_didact' => '1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-82-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-92',
                'telefonos' => '7437415088 ext 106 Cel. 7751048997',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables.',
                'equipo_electr' => '1 laptop, 1 proyector, 1 Pantalla de 50"',
                'material_didact' => '1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-83-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-93',
                'telefonos' => 'Tel: 7437415014 (Zempoala)- Casa particular Tel: 7717185323 (Consultorio Pachuca) Cel: 7712547079',
                'dias_hora_aten' => 'LUN-SAB 9:00 - 4:00 PM',
                'equipo_movil' => ' 1 Escritorio, 1 Silla Secretarial, 1 mesa tablón, 6 sillas plegables. ',
                'equipo_electr' => '1 laptop, 1 proyector, 1 Pantalla de 50"',
                'material_didact' => '1 maqueta mantos acuíferos, 1 maqueta de relleno sanitario, 1 super del agua, 1 quiz del agua, 1 lentes de RV, 1  placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-83-1-2'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-94',
                'telefonos' => '7721514670',
                'dias_hora_aten' => 'LUN-SAB 9:00 - 5:00 PM',
                'equipo_movil' => ' 1 escritorio secretarial,  1 silla secretarial, 1 archivero, 1 Mesa Plegable y  5 sillas Plegables',
                'equipo_electr' => ' 2  laptop, 2   proyector, 1 equipo de perifoneo, 2  cámaras fotográficas, 1  equipo de sonido, 1 impresora, 1 computadora de escritorio, 1 DVD, 1 pantalla de 33 pulgadas, 1 Televisor de 50" ',
                'material_didact' => '1 maqueta mantos acuíferos, 1 maqueta contaminación de una cuenca, 1 Casco de Realidad virtual ,1 Quiz del Agua, 1 súper del agua, 1 placa de identificación',
                'comentarios' => 'Los ECAS, generalmente atienden a la población de las cabeceras municipales y comunidades cercanas.',
                'id_estatus' => 'EST-1K2LMP4X',
                'clave_eca' => '13-84-1-1'
            ],
            [
                'id_detalle_eca' => 'DET-ECA-95',
                'telefonos' => '"7717112044 Ext. 126 7717115564 Cel: 7712061900',
                'dias_hora_aten' => 'LUN-VIER 8:30 AM - 04:00 PM',
                'equipo_movil' => '1 escritorio secretarial,1  silla secretarial, ',
                'equipo_electr' => '1 cámara fotográfica, 1 mini laptop,1 impresora,1 proyector, 1 equipo de sonido, 1 pantalla 32" y 1 mesa interactiva ',
                'material_didact' => 'Maqueta Contaminación de una Cuenca, maqueta Mantos Acuíferos, maqueta Potabilización y Drenaje, maqueta de Relleno Sanitario, maqueta Ciclo del Agua 3D.',
                'comentarios' => 'Cerrado.',
                'id_estatus' => 'EST-C731KSDA',
                'clave_eca' => '13-48-1-8'
            ],
        ]);
    }
}
