<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DireccionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('direccion')->insert([
            [
                'id_direccion' => 'DIR-1',
                'cod_postal' => '43540',
                'localidad' => 'Acatlán',
                'colonia' => 'Centro',
                'calle_av' => '16 de enero',
                'num_direccion' => '14',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-1',
            ],
            [
                'id_direccion' => 'DIR-10',
                'cod_postal' => '42970',
                'localidad' => 'Atitalaquia',
                'colonia' => 'Centro',
                'calle_av' => 'Del Arco',
                'num_direccion' => '5',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-10',
            ],
            [
                'id_direccion' => 'DIR-11',
                'cod_postal' => '43060',
                'localidad' => 'Atlapexco',
                'colonia' => 'Centro',
                'calle_av' => 'Pino',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-11',
            ],
            [
                'id_direccion' => 'DIR-12',
                'cod_postal' => '43300',
                'localidad' => 'Atotonilco el Grande',
                'colonia' => 'Centro',
                'calle_av' => 'Plaza principal',
                'num_direccion' => '334',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-12',
            ],
            [
                'id_direccion' => 'DIR-13',
                'cod_postal' => '42980',
                'localidad' => 'Atotonilco de Tula',
                'colonia' => 'Los Compadres',
                'calle_av' => 'Republica de Cuba',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-13',
            ],
            [
                'id_direccion' => 'DIR-14',
                'cod_postal' => '43233',
                'localidad' => 'Calnali',
                'colonia' => 'Centro',
                'calle_av' => 'Av. Juarez',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-14',
            ],
            [
                'id_direccion' => 'DIR-15',
                'cod_postal' => '42370',
                'localidad' => 'Cardonal',
                'colonia' => 'centro',
                'calle_av' => 'BENITO PABLO JUAREZ GARCIA',
                'num_direccion' => '4',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-15',
            ],
            [
                'id_direccion' => 'DIR-16',
                'cod_postal' => '43740',
                'localidad' => 'Cuautepec de Hinojosa',
                'colonia' => 'Centro',
                'calle_av' => 'Benito Juárez',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-16',
            ],
            [
                'id_direccion' => 'DIR-17',
                'cod_postal' => '42900',
                'localidad' => 'Chapantongo',
                'colonia' => 'Barrio Guadalupe',
                'calle_av' => 'Palacio Municipal',
                'num_direccion' => '34',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-17',
            ],
            [
                'id_direccion' => 'DIR-18',
                'cod_postal' => '42280',
                'localidad' => 'Chapulhuacá',
                'colonia' => 'Centro',
                'calle_av' => 'Francisco Sarabia',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-18',
            ],
            [
                'id_direccion' => 'DIR-19',
                'cod_postal' => '42750',
                'localidad' => 'Chilcuautla',
                'colonia' => 'Centro',
                'calle_av' => 'Diesiseis de enero',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-19',
            ],
            [
                'id_direccion' => 'DIR-2',
                'cod_postal' => '43720',
                'localidad' => 'Acaxochitlán',
                'colonia' => 'Centro',
                'calle_av' => 'Matamoros',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-2',
            ],
            [
                'id_direccion' => 'DIR-20',
                'cod_postal' => '43330',
                'localidad' => 'Eloxochitlá',
                'colonia' => 'Centro',
                'calle_av' => '16 de septiembre',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-20',
            ],
            [
                'id_direccion' => 'DIR-21',
                'cod_postal' => '43960',
                'localidad' => 'Emiliano Zapata',
                'colonia' => 'Centro',
                'calle_av' => '5 de mayo',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-21',
            ],
            [
                'id_direccion' => 'DIR-22',
                'cod_postal' => '43580',
                'localidad' => 'Epazoyucan',
                'colonia' => 'Centro',
                'calle_av' => 'Carretera Hidalgo',
                'num_direccion' => '11',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-22',
            ],
            [
                'id_direccion' => 'DIR-23',
                'cod_postal' => '42660',
                'localidad' => 'Tepatepec',
                'colonia' => 'CENTRO',
                'calle_av' => 'EMILIANO ZAPATA',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-23',
            ],
            [
                'id_direccion' => 'DIR-24',
                'cod_postal' => '42660',
                'localidad' => 'Francisco I. Madero',
                'colonia' => 'CENTRO',
                'calle_av' => 'Corregidora',
                'num_direccion' => '27',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-23',
            ],
            [
                'id_direccion' => 'DIR-25',
                'cod_postal' => '43500',
                'localidad' => 'Huasca de Ocampo',
                'colonia' => 'CENTRO',
                'calle_av' => 'ALDAMA',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-24',
            ],
            [
                'id_direccion' => 'DIR-26',
                'cod_postal' => '43050',
                'localidad' => 'Huautla',
                'colonia' => 'CENTRO',
                'calle_av' => 'ARQ. GUILLERMO ROSELL DE LA LAMA',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-25',
            ],
            [
                'id_direccion' => 'DIR-27',
                'cod_postal' => '43070',
                'localidad' => 'Huazalingo',
                'colonia' => 'Centro',
                'calle_av' => 'AV. HIDALGO',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-26',
            ],
            [
                'id_direccion' => 'DIR-28',
                'cod_postal' => '43420',
                'localidad' => 'Huehuetla',
                'colonia' => 'Centro',
                'calle_av' => 'Luis Donaldo Colosio',
                'num_direccion' => '330',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-27',
            ],
            [
                'id_direccion' => 'DIR-29',
                'cod_postal' => '43000',
                'localidad' => 'Huejutla de Reyes',
                'colonia' => 'Centro',
                'calle_av' => 'NICANDRO CASTILLO',
                'num_direccion' => '25',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-28',
            ],
            [
                'id_direccion' => 'DIR-3',
                'cod_postal' => '42500',
                'localidad' => 'Actopan',
                'colonia' => 'Aviación',
                'calle_av' => 'Alonso de Borja',
                'num_direccion' => '201',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-3',
            ],
            [
                'id_direccion' => 'DIR-30',
                'cod_postal' => '43000',
                'localidad' => 'Huejutla de Reyes',
                'colonia' => 'Tepoxtequito',
                'calle_av' => 'PARQUE INDUSTRIAL SIGLO XXI',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Otro',
                'id_municipio' => 'MUN-28',
            ],
            [
                'id_direccion' => 'DIR-31',
                'cod_postal' => '42400',
                'localidad' => 'Huichapan',
                'colonia' => 'Barrio el Calvario',
                'calle_av' => 'NICOLAS BRAVO',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-29',
            ],
            [
                'id_direccion' => 'DIR-32',
                'cod_postal' => '42400',
                'localidad' => 'Huichapan',
                'colonia' => 'Centro Historico',
                'calle_av' => 'MANUEL CHAVEZ NAVA',
                'num_direccion' => '3',
                'tipo_instancia' => 'Órganos de participación previstos en la LAN',
                'id_municipio' => 'MUN-29',
            ],
            [
                'id_direccion' => 'DIR-33',
                'cod_postal' => '42300',
                'localidad' => 'Ixmiquilpan',
                'colonia' => 'CENTRO',
                'calle_av' => 'FELIPE ÁNGELES',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Órganos de participación previstos en la LAN',
                'id_municipio' => 'MUN-30',
            ],
            [
                'id_direccion' => 'DIR-34',
                'cod_postal' => '42200',
                'localidad' => 'Jacala',
                'colonia' => 'Centro',
                'calle_av' => 'PINO SUAREZ',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Órganos de participación previstos en la LAN',
                'id_municipio' => 'MUN-31',
            ],
            [
                'id_direccion' => 'DIR-35',
                'cod_postal' => '43040',
                'localidad' => 'Jaltocán',
                'colonia' => 'Centro',
                'calle_av' => 'Felipe Ángeles',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-32',
            ],
            [
                'id_direccion' => 'DIR-36',
                'cod_postal' => '43190',
                'localidad' => 'Juárez',
                'colonia' => 'Centro',
                'calle_av' => 'Avenida Juárez',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-33',
            ],
            [
                'id_direccion' => 'DIR-37',
                'cod_postal' => '43140',
                'localidad' => 'Lolotla',
                'colonia' => 'Centro',
                'calle_av' => 'Benito Juárez',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-34',
            ],
            [
                'id_direccion' => 'DIR-38',
                'cod_postal' => '43400',
                'localidad' => 'Metepec',
                'colonia' => 'Centro',
                'calle_av' => 'Diesiseis de septiembre',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-35',
            ],
            [
                'id_direccion' => 'DIR-39',
                'cod_postal' => '43380',
                'localidad' => 'Metzquititlán',
                'colonia' => 'CENTRO',
                'calle_av' => 'NIÑOS HEROES',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-36',
            ],
            [
                'id_direccion' => 'DIR-4',
                'cod_postal' => '43460',
                'localidad' => 'Agua Blanca Iturbide',
                'colonia' => 'Centro',
                'calle_av' => 'Allende',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-4',
            ],
            [
                'id_direccion' => 'DIR-40',
                'cod_postal' => '43351',
                'localidad' => 'Metztitlán',
                'colonia' => 'Centro',
                'calle_av' => 'Porfirio Díaz',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-37',
            ],
            [
                'id_direccion' => 'DIR-41',
                'cod_postal' => '42120',
                'localidad' => 'Mineral del Chico',
                'colonia' => 'Centro',
                'calle_av' => 'plaza principal',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-38',
            ],
            [
                'id_direccion' => 'DIR-42',
                'cod_postal' => '42133',
                'localidad' => 'Mineral del Monte',
                'colonia' => 'Industrial',
                'calle_av' => 'Porfirio Díaz',
                'num_direccion' => '200',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-40',
            ],
            [
                'id_direccion' => 'DIR-43',
                'cod_postal' => '42260',
                'localidad' => 'La Misión',
                'colonia' => 'Centro',
                'calle_av' => 'Plaza Juárez',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-39',
            ],
            [
                'id_direccion' => 'DIR-44',
                'cod_postal' => '42700',
                'localidad' => 'Mixquiahuala',
                'colonia' => 'Centro',
                'calle_av' => 'Gómez Faríaz',
                'num_direccion' => '15',
                'tipo_instancia' => 'Órganos de participación previstos en la LAN',
                'id_municipio' => 'MUN-41',
            ],
            [
                'id_direccion' => 'DIR-45',
                'cod_postal' => '43100',
                'localidad' => 'Molango',
                'colonia' => 'Centro',
                'calle_av' => 'Ignacio Zaragoza',
                'num_direccion' => '1',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-42',
            ],
            [
                'id_direccion' => 'DIR-46',
                'cod_postal' => '42360',
                'localidad' => 'Nicolás Flores',
                'colonia' => 'Centro',
                'calle_av' => 'Profr. Muriño Muñóz Basilio',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-43',
            ],
            [
                'id_direccion' => 'DIR-47',
                'cod_postal' => '42470',
                'localidad' => 'Nopala',
                'colonia' => 'Centro',
                'calle_av' => 'Avenida del Trabajo',
                'num_direccion' => '5',
                'tipo_instancia' => 'Órganos de participación previstos en la LAN',
                'id_municipio' => 'MUN-44',
            ],
            [
                'id_direccion' => 'DIR-48',
                'cod_postal' => '43560',
                'localidad' => 'Omitlán de Juárez',
                'colonia' => 'Centro',
                'calle_av' => 'Juárez',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-45',
            ],
            [
                'id_direccion' => 'DIR-49',
                'cod_postal' => '43020',
                'localidad' => 'Orizatlán',
                'colonia' => 'CENTRO',
                'calle_av' => 'GUSTAVO ARVIZU AVILA',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-46',
            ],
            [
                'id_direccion' => 'DIR-5',
                'cod_postal' => '42150',
                'localidad' => 'Ajacuba',
                'colonia' => 'Centro',
                'calle_av' => 'Eustolia Becerra',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-5',
            ],
            [
                'id_direccion' => 'DIR-50',
                'cod_postal' => '42240',
                'localidad' => 'Pacula',
                'colonia' => 'Centro',
                'calle_av' => 'Benito Juárez',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-47',
            ],
            [
                'id_direccion' => 'DIR-51',
                'cod_postal' => '42092',
                'localidad' => 'Pachuca de Soto',
                'colonia' => 'Zona Industrial La Paz',
                'calle_av' => 'INDUSTRIAL LA PAZ',
                'num_direccion' => '200',
                'tipo_instancia' => 'Organismo Operador Intermunicipal',
                'id_municipio' => 'MUN-48',
            ],
            [
                'id_direccion' => 'DIR-52',
                'cod_postal' => '42084',
                'localidad' => 'Pachuca de Soto',
                'colonia' => 'Zona Plateada',
                'calle_av' => '0',
                'num_direccion' => '431',
                'tipo_instancia' => 'Órganos de participación previstos en la LAN',
                'id_municipio' => 'MUN-48',
            ],
            [
                'id_direccion' => 'DIR-53',
                'cod_postal' => '42082',
                'localidad' => 'Pachuca de Soto',
                'colonia' => 'Zona Plateada',
                'calle_av' => 'Camino Real de la plata',
                'num_direccion' => '336',
                'tipo_instancia' => 'Órganos de participación previstos en la LAN',
                'id_municipio' => 'MUN-48',
            ],
            [
                'id_direccion' => 'DIR-54',
                'cod_postal' => '42000',
                'localidad' => 'Centro',
                'colonia' => 'Pachuca de Soto',
                'calle_av' => 'Plaza Pedro Ma. Anaya',
                'num_direccion' => '1',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-48',
            ],
            [
                'id_direccion' => 'DIR-55',
                'cod_postal' => '42220',
                'localidad' => 'Pisaflores',
                'colonia' => 'Centro',
                'calle_av' => 'Veinte de noviembre',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-49',
            ],
            [
                'id_direccion' => 'DIR-56',
                'cod_postal' => '42730',
                'localidad' => 'Progreso',
                'colonia' => 'CENTRO',
                'calle_av' => 'Nuevo México',
                'num_direccion' => '22-A',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-50',
            ],
            [
                'id_direccion' => 'DIR-57',
                'cod_postal' => '42180',
                'localidad' => 'Mineral de la Reforma',
                'colonia' => 'Santa María la Calera',
                'calle_av' => 'Calle Diamante',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-51',
            ],
            [
                'id_direccion' => 'DIR-58',
                'cod_postal' => '42160',
                'localidad' => 'San Agustín Tlaxiaca',
                'colonia' => 'CENTRO',
                'calle_av' => 'AVENIDA INDEPENDENCIA',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-52',
            ],
            [
                'id_direccion' => 'DIR-59',
                'cod_postal' => '43440',
                'localidad' => 'Tutotepec',
                'colonia' => 'CENTRO',
                'calle_av' => 'BENITO JUÁREZ',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-53',
            ],
            [
                'id_direccion' => 'DIR-6',
                'cod_postal' => '42390',
                'localidad' => 'Alfajayucan',
                'colonia' => 'Centro',
                'calle_av' => 'Palacio Municipal',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-6',
            ],
            [
                'id_direccion' => 'DIR-60',
                'cod_postal' => '42650',
                'localidad' => 'San Salvador',
                'colonia' => 'San Antonio Zaragoza',
                'calle_av' => 'AV. FELIPE ÁNGELES',
                'num_direccion' => '10',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-59',
            ],
            [
                'id_direccion' => 'DIR-61',
                'cod_postal' => '42640',
                'localidad' => 'San Salvador',
                'colonia' => 'Centro',
                'calle_av' => 'Calle Ayuntamiento',
                'num_direccion' => '1',
                'tipo_instancia' => 'Sistemas de Agua',
                'id_municipio' => 'MUN-59',
            ],
            [
                'id_direccion' => 'DIR-62',
                'cod_postal' => '42620',
                'localidad' => 'El Centro',
                'colonia' => 'Gonzalez Gonzalez',
                'calle_av' => 'Frente a la iglesia',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-60',
            ],
            [
                'id_direccion' => 'DIR-63',
                'cod_postal' => '43760',
                'localidad' => 'Santiago Tulantepec',
                'colonia' => 'Centro',
                'calle_av' => 'Cerrada 1o. de abril',
                'num_direccion' => '92',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-61',
            ],
            [
                'id_direccion' => 'DIR-64',
                'cod_postal' => '43780',
                'localidad' => 'Singuilucan',
                'colonia' => 'Centro',
                'calle_av' => 'Plaza del Artículo 115',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-62',
            ],
            [
                'id_direccion' => 'DIR-65',
                'cod_postal' => '42380',
                'localidad' => 'Tasquillo',
                'colonia' => 'Centro',
                'calle_av' => 'Fernando Soto',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-54',
            ],
            [
                'id_direccion' => 'DIR-66',
                'cod_postal' => '42440',
                'localidad' => 'Tecozautla',
                'colonia' => 'Barrio Hidalgo',
                'calle_av' => 'Calzada de Guadalupe',
                'num_direccion' => '26',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-55',
            ],
            [
                'id_direccion' => 'DIR-67',
                'cod_postal' => '43480',
                'localidad' => 'Tenango de Doria',
                'colonia' => 'CENTRO',
                'calle_av' => 'AV. BENITO JUÁRE',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-56',
            ],
            [
                'id_direccion' => 'DIR-68',
                'cod_postal' => '43970',
                'localidad' => 'Tepeapulco',
                'colonia' => 'CENTRO',
                'calle_av' => 'BENITO JUÁRE',
                'num_direccion' => '8',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-57',
            ],
            [
                'id_direccion' => 'DIR-69',
                'cod_postal' => '43120',
                'localidad' => 'Tepehuacán de Guerrero',
                'colonia' => 'Centro',
                'calle_av' => 'Av. Democracia',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-58',
            ],
            [
                'id_direccion' => 'DIR-7',
                'cod_postal' => '43940',
                'localidad' => 'Almoloya',
                'colonia' => 'Centro',
                'calle_av' => 'Pino',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-7',
            ],
            [
                'id_direccion' => 'DIR-70',
                'cod_postal' => '42850',
                'localidad' => 'Tepeji de Ocampo',
                'colonia' => 'San Francisco',
                'calle_av' => 'IGNACIO COMOFORT',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-63',
            ],
            [
                'id_direccion' => 'DIR-71',
                'cod_postal' => '42920',
                'localidad' => 'Tepetitlán',
                'colonia' => 'Centro',
                'calle_av' => 'Tepetitlán - Tula de Allende',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-64',
            ],
            [
                'id_direccion' => 'DIR-72',
                'cod_postal' => '42940',
                'localidad' => 'Tetepango',
                'colonia' => 'Centro',
                'calle_av' => 'Av. 16 de enero',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-65',
            ],
            [
                'id_direccion' => 'DIR-73',
                'cod_postal' => '43880',
                'localidad' => 'Tezontepec',
                'colonia' => 'CENTRO',
                'calle_av' => 'DIESCISEIS DE ENERO',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-66',
            ],
            [
                'id_direccion' => 'DIR-74',
                'cod_postal' => '42760',
                'localidad' => 'Tezontepec de Aldama',
                'colonia' => 'CENTRO',
                'calle_av' => 'AV. ALLENDE',
                'num_direccion' => '5',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-67',
            ],
            [
                'id_direccion' => 'DIR-75',
                'cod_postal' => '43270',
                'localidad' => 'Tianguistengo',
                'colonia' => 'CENTRO',
                'calle_av' => 'RUPERTO ALARCON',
                'num_direccion' => '11',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-68',
            ],
            [
                'id_direccion' => 'DIR-76',
                'cod_postal' => '43800',
                'localidad' => 'Tizayuca',
                'colonia' => 'El Pedregal',
                'calle_av' => 'Av. Juárez Norte',
                'num_direccion' => '39',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-69',
            ],
            [
                'id_direccion' => 'DIR-77',
                'cod_postal' => '42780',
                'localidad' => 'Tlahuelilpan',
                'colonia' => 'CENTRO',
                'calle_av' => 'Av. Del Ejido',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-70',
            ],
            [
                'id_direccion' => 'DIR-78',
                'cod_postal' => '43170',
                'localidad' => 'Tlahuiltepa',
                'colonia' => 'Centro',
                'calle_av' => 'Avenida principal',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-71',
            ],
            [
                'id_direccion' => 'DIR-79',
                'cod_postal' => '43930',
                'localidad' => 'Tlanalapa',
                'colonia' => 'CENTRO',
                'calle_av' => 'GERARDO ROLDAN NORTE',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-72',
            ],
            [
                'id_direccion' => 'DIR-8',
                'cod_postal' => '43900',
                'localidad' => 'Apan',
                'colonia' => 'Centro',
                'calle_av' => 'Lauro L. Mendez',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-8',
            ],
            [
                'id_direccion' => 'DIR-80',
                'cod_postal' => '43150',
                'localidad' => 'Tlanchinol',
                'colonia' => 'CENTRO',
                'calle_av' => 'J GONZALEZ',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-78',
            ],
            [
                'id_direccion' => 'DIR-81',
                'cod_postal' => '42950',
                'localidad' => 'Tlaxcoapan',
                'colonia' => 'Centro',
                'calle_av' => 'Av. Juárez',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-79',
            ],
            [
                'id_direccion' => 'DIR-82',
                'cod_postal' => '43860',
                'localidad' => 'Tolcayuca',
                'colonia' => 'Centro',
                'calle_av' => 'Juárez',
                'num_direccion' => '1',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-80',
            ],
            [
                'id_direccion' => 'DIR-83',
                'cod_postal' => '42800',
                'localidad' => 'Tula de Allende',
                'colonia' => 'CENTRO',
                'calle_av' => 'MELCHOR OCAMPO',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-73',
            ],
            [
                'id_direccion' => 'DIR-84',
                'cod_postal' => '43640',
                'localidad' => 'Tulancingo',
                'colonia' => 'Fracc. Nuevo San Nicolas',
                'calle_av' => 'Blv. San Nicolas',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-74',
            ],
            [
                'id_direccion' => 'DIR-85',
                'cod_postal' => '43640',
                'localidad' => 'Tulancingo',
                'colonia' => 'Fracc. Nuevo San Nicolas',
                'calle_av' => 'Blv. San Nicolas',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-74',
            ],
            [
                'id_direccion' => 'DIR-86',
                'cod_postal' => '43760',
                'localidad' => 'Tulancingo',
                'colonia' => 'Francisco I Madero',
                'calle_av' => 'VENUSTIANO CARRANZA',
                'num_direccion' => '402',
                'tipo_instancia' => 'Órganos de participación previstos en la LAN',
                'id_municipio' => 'MUN-74',
            ],
            [
                'id_direccion' => 'DIR-87',
                'cod_postal' => '43090',
                'localidad' => 'Xochiatipan',
                'colonia' => 'CENTRO',
                'calle_av' => 'INDEPENDENCIA',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-75',
            ],
            [
                'id_direccion' => 'DIR-88',
                'cod_postal' => '43250',
                'localidad' => 'Xochicoatlán',
                'colonia' => 'CENTRO',
                'calle_av' => 'MINA',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-76',
            ],
            [
                'id_direccion' => 'DIR-89',
                'cod_postal' => '43080',
                'localidad' => 'Yahualica',
                'colonia' => 'Centro',
                'calle_av' => 'Hidalgo',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-77',
            ],
            [
                'id_direccion' => 'DIR-9',
                'cod_postal' => '42680',
                'localidad' => 'El Arenal',
                'colonia' => 'Centro',
                'calle_av' => 'Palacio Municipal',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-9',
            ],
            [
                'id_direccion' => 'DIR-90',
                'cod_postal' => '43200',
                'localidad' => 'Zacualtipán',
                'colonia' => 'CENTRO',
                'calle_av' => 'Plaza de la Constitución',
                'num_direccion' => 'S/N',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-81',
            ],
            [
                'id_direccion' => 'DIR-91',
                'cod_postal' => '42190',
                'localidad' => 'Zapotlán de Juárez',
                'colonia' => 'Centro',
                'calle_av' => 'Av. Hidalgo',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-82',
            ],
            [
                'id_direccion' => 'DIR-92',
                'cod_postal' => '43830',
                'localidad' => 'Zempoala',
                'colonia' => 'Centro',
                'calle_av' => 'Hidalgo',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Municipio',
                'id_municipio' => 'MUN-83',
            ],
            [
                'id_direccion' => 'DIR-93',
                'cod_postal' => '43830',
                'localidad' => 'Zempoala',
                'colonia' => 'Centro',
                'calle_av' => 'Abasolo',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Otro',
                'id_municipio' => 'MUN-83',
            ],
            [
                'id_direccion' => 'DIR-94',
                'cod_postal' => '42330',
                'localidad' => 'Zimapán',
                'colonia' => 'Centro',
                'calle_av' => 'H. Colegio Militar',
                'num_direccion' => '4',
                'tipo_instancia' => 'Organismo Operador Municipal',
                'id_municipio' => 'MUN-84',
            ],
            [
                'id_direccion' => 'DIR-95',
                'cod_postal' => '42080',
                'localidad' => 'Pachuca de Soto',
                'colonia' => 'Venta Prieta',
                'calle_av' => 'Boulevard Felipe Angeles',
                'num_direccion' => 's/n',
                'tipo_instancia' => 'Museo Interactivo "El Rehilete"',
                'id_municipio' => 'MUN-48',
            ]
        ]);
    }
}
