<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EcaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos = DB::table('eca')->insert([
            [
                'clave_eca' => '13-1-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable Municipal',
                'poblacion_atend' => 439,
                'fecha_apert' => '2004-12-13',
                'fecha_forta' => '2023-12-28',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-1',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-1',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-2-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable Municipal',
                'poblacion_atend' => 250,
                'fecha_apert' => '2002-12-09',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-2',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-2',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-3-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua y Alcantarillado del municipio de Actopan (CAASA)',
                'poblacion_atend' => 32276,
                'fecha_apert' => '2004-12-13',
                'fecha_forta' => '2023-12-27',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-3',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-3',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-4-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable Municipal',
                'poblacion_atend' => 2325,
                'fecha_apert' => '2003-11-03',
                'fecha_forta' => '2025-12-18',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-4',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-4',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-5-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua y Saneamiento del municipio de Ajacuba (CAYSA)',
                'poblacion_atend' => 8254,
                'fecha_apert' => '2004-10-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-5',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-5',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-6-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua y Alcantarillado del municipio de Alfajayucan (CAAMAH)',
                'poblacion_atend' => 1794,
                'fecha_apert' => '2004-10-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-6',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-6',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-7-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable del municipio de Almoloya (COMAAL)',
                'poblacion_atend' => 5618,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-7',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-7',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-8-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable y Alcantarillado del municipio de Apan (CAAPAN)',
                'poblacion_atend' => 28792,
                'fecha_apert' => '2001-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-8',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-8',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-9-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 3578,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-9',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-9',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-10-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable, Alcantarillado y Saneamiento del municipio de Atitalaquia (CAPASMAH)',
                'poblacion_atend' => 6924,
                'fecha_apert' => '2003-04-15',
                'fecha_forta' => '2023-12-27',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-10',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-10',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-11-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Ecología',
                'poblacion_atend' => 2960,
                'fecha_apert' => '2001-11-26',
                'fecha_forta' => '2025-12-19',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-11',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-11',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-12-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 8417,
                'fecha_apert' => '2003-11-03',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-12',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-12',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-13-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable, Alcantarillado y Saneamiento del municipio de Atotonilco de Tula (CAASAT)',
                'poblacion_atend' => 8822,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-13',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-13',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-14-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable y Alcantarillado del municipio de Calnali  (CAPAC)',
                'poblacion_atend' => 4235,
                'fecha_apert' => '2002-10-14',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-14',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-14',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-15-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Organismo Descentralizado de Agua Potable y Alcantarillado de Cardonal M´Oahi (ODAPYAC)',
                'poblacion_atend' => 755,
                'fecha_apert' => '2002-10-14',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-15',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-15',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-16-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable, Alcantarillado y Saneamiento del municipio de Cuautepec de Hinojosa, Hidalgo (CAPASCHH)',
                'poblacion_atend' => 20530,
                'fecha_apert' => '2002-09-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-16',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-16',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-17-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Sistema de Agua Potable Chapantongo (SAPC)',
                'poblacion_atend' => 2006,
                'fecha_apert' => '2003-10-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-17',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-17',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-18-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Servicios Públicos Municipales',
                'poblacion_atend' => 4054,
                'fecha_apert' => '2003-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-18',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-18',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-19-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Servicios Municipales',
                'poblacion_atend' => 1262,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-19',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-19',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-20-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 601,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2025-12-17',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-20',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-20',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-21-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 9584,
                'fecha_apert' => '2002-10-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-21',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-21',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-22-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Ecología',
                'poblacion_atend' => 3310,
                'fecha_apert' => '2003-04-15',
                'fecha_forta' => '2025-12-18',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-22',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-22',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-23-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 11335,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-23',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-23',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-23-1-2',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua y Alcantarillado del Sistema Valle del Mezquital (CAASVAM)',
                'poblacion_atend' => 11335,
                'fecha_apert' => '2006-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-24',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-24',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-24-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua del Municipio de Huasca de Ocampo (COAMH)',
                'poblacion_atend' => 417,
                'fecha_apert' => '2002-12-01',
                'fecha_forta' => '2023-12-27',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-25',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-25',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-25-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable, Alcantarillado y Saneamiento del municipio de Huautla (CAASH)',
                'poblacion_atend' => 3806,
                'fecha_apert' => '2003-11-03',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-26',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-26',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-26-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable y Ecología Municipal',
                'poblacion_atend' => 770,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2025-12-17',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-27',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-27',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-27-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 2993,
                'fecha_apert' => '2003-12-19',
                'fecha_forta' => '2025-12-18',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-28',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-28',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-28-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable, Alcantarillado y Saneamineto de Huejutla, Hidalgo (CAPASHH)',
                'poblacion_atend' => 44311,
                'fecha_apert' => '2003-12-01',
                'fecha_forta' => '2023-12-27',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-29',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-29',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-28-1-4',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Universidad Politécnica de Huejutla',
                'poblacion_atend' => 800,
                'fecha_apert' => '2016-12-23',
                'fecha_forta' => '2025-12-18',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-30',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-30',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-29-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable, Alcantarillado y Saneamiento del municipio de Huichapan (CAPOSA)',
                'poblacion_atend' => 9853,
                'fecha_apert' => '2004-12-13',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-31',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-31',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-29-1-2',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comité Técnico de Aguas Subterraneas (Huichapan-Tecozautla-Nopala)-(COTAS)',
                'poblacion_atend' => 9853,
                'fecha_apert' => '2006-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-32',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-32',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-30-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable, Alcantarillado y Saneamiento del municipio de Ixmiquilpan (CAPASMIH)',
                'poblacion_atend' => 37608,
                'fecha_apert' => '2003-04-15',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-33',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-33',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-31-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable, Alcantarillado y Saneamiento del Municipio de Jacala de Ledezma (CAPASJ)',
                'poblacion_atend' => 4582,
                'fecha_apert' => '2002-04-08',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-34',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-34',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-32-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Obras públicas',
                'poblacion_atend' => 5919,
                'fecha_apert' => '2001-09-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-35',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-35',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-33-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 616,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2025-12-17',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-36',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-36',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-34-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 590,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2025-12-19',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-37',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-37',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-35-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 2248,
                'fecha_apert' => '2003-11-03',
                'fecha_forta' => '2025-12-17',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-38',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-38',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-36-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 1788,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-39',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-39',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-37-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 3274,
                'fecha_apert' => '2003-10-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-40',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-40',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-38-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Obras Púbicas',
                'poblacion_atend' => 533,
                'fecha_apert' => '2001-09-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-41',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-41',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-39-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Ecología',
                'poblacion_atend' => 1813,
                'fecha_apert' => '2003-04-15',
                'fecha_forta' => '2025-12-18',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-42',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-42',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-40-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Obras Publicas y Ecología Municipal',
                'poblacion_atend' => 546,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2025-12-17',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-43',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-43',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-41-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comision de Agua y Alcantarillado del Municipio de Mixquiahuala, Hgo',
                'poblacion_atend' => 27713,
                'fecha_apert' => '2003-11-01',
                'fecha_forta' => '2023-12-27',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-44',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-44',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-42-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 4995,
                'fecha_apert' => '2001-11-01',
                'fecha_forta' => '2025-12-17',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-45',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-45',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-43-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable  y Saneamiento del Municipio de Nicolás Flores',
                'poblacion_atend' => 404,
                'fecha_apert' => '2003-10-01',
                'fecha_forta' => '2025-12-17',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-46',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-46',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-44-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable, Alcantarillado y Saneamiento del municipio de Nopala (ODAPAN)',
                'poblacion_atend' => 1155,
                'fecha_apert' => '2002-10-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-47',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-47',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-45-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 1050,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-48',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-48',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-46-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Ecología',
                'poblacion_atend' => 7037,
                'fecha_apert' => '2002-10-01',
                'fecha_forta' => '2025-12-18',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-49',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-49',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-47-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 540,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2024-09-24',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-50',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-50',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-48-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comision de Agua y Alcantarillado Sistemas Intermunicipales (CAASIM)',
                'poblacion_atend' => 125000,
                'fecha_apert' => '2003-11-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-51',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-51',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-48-1-3',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión Nacional del Agua (CONAGUA)',
                'poblacion_atend' => 150000,
                'fecha_apert' => '2006-12-01',
                'fecha_forta' => '2023-12-27',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-52',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-52',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-48-1-4',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo (CEAA)',
                'poblacion_atend' => 150000,
                'fecha_apert' => '2006-12-01',
                'fecha_forta' => '2023-12-27',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-53',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-53',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-48-1-6',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Presidencia Municipal de Pachuca',
                'poblacion_atend' => 297848,
                'fecha_apert' => '2008-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-54',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-54',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-48-1-8',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Museo Interactivo "El Rehilete"',
                'poblacion_atend' => 416000,
                'fecha_apert' => '2011-08-10',
                'fecha_forta' => '2019-11-28',
                'fecha_cierre' => '2025-12-10',
                'motivo_cierre' => 'Enviaron oficio de cierre definitivo del espacio de cultura del agua',
                'ruta_logo' => '',
                'id_usuario' => 'USER-95',
                'id_estatus' => 'EST-C731KSDA',
                'id_direccion' => 'DIR-95',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-49-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Servicios Públicos y Ecología',
                'poblacion_atend' => 2428,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2025-12-17',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-55',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-55',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-50-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua y Alcantarillado de Progreso de Alvaro Obregón (CAAMPAO)',
                'poblacion_atend' => 17718,
                'fecha_apert' => '2002-11-29',
                'fecha_forta' => '2023-12-27',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-56',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-56',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-51-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Medio Ambiente',
                'poblacion_atend' => 9559,
                'fecha_apert' => '2003-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-57',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-57',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-52-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable, Alcantarillado y Saneamiento del municipio de San Agustín Tlaxiaca (CAPASSAT)',
                'poblacion_atend' => 12328,
                'fecha_apert' => '2003-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-58',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-58',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-53-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 2764,
                'fecha_apert' => '2003-12-01',
                'fecha_forta' => '2023-12-27',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-59',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-59',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-54-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua y Alcantarillado del municipio de San Salvador, Hgo. (CAAMSSH)',
                'poblacion_atend' => 1107,
                'fecha_apert' => '2003-10-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-60',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-60',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-54-23-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Sistema de Agua Potable Teofani',
                'poblacion_atend' => 1107,
                'fecha_apert' => '2006-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-61',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-61',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-55-1-2',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable y Alcantarillado de Santiago de Anaya',
                'poblacion_atend' => 2676,
                'fecha_apert' => '2002-10-25',
                'fecha_forta' => '2023-12-27',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-62',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-62',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-56-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable, Alcantarillado y Saneamiento de Tulantepec  (CAASST)',
                'poblacion_atend' => 17449,
                'fecha_apert' => '2002-10-07',
                'fecha_forta' => '2023-12-27',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-63',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-63',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-57-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Ecología',
                'poblacion_atend' => 4805,
                'fecha_apert' => '2004-12-13',
                'fecha_forta' => '2025-12-17',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-64',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-64',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-58-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 4030,
                'fecha_apert' => '2003-11-05',
                'fecha_forta' => '2025-12-18',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-65',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-65',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-59-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comision de Agua Potable, Alcantarillado y Saneamiento del Municipio de Tecozautla (CAAST)',
                'poblacion_atend' => 6701,
                'fecha_apert' => '2002-11-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-66',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-66',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-60-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Ecología',
                'poblacion_atend' => 2614,
                'fecha_apert' => '2003-10-01',
                'fecha_forta' => '2025-12-18',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-67',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-67',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-61-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 16368,
                'fecha_apert' => '2002-09-01',
                'fecha_forta' => '2025-12-18',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-68',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-68',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-62-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección De Agua Potable y alcantarillado',
                'poblacion_atend' => 1373,
                'fecha_apert' => '2004-12-13',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-69',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-69',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-63-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua y Alcantarillado del municipio de Tepeji del Río de Ocampo, Hgo. (CAAMTROH)',
                'poblacion_atend' => 36618,
                'fecha_apert' => '2003-10-18',
                'fecha_forta' => '2023-12-28',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-70',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-70',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-64-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Ecología de Agua Potable',
                'poblacion_atend' => 1056,
                'fecha_apert' => '2003-12-19',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-71',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-71',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-65-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Direccion de Agua Potable y Ecología',
                'poblacion_atend' => 9145,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-72',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-72',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-66-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Municipio de Villa de Tezontepec',
                'poblacion_atend' => 6213,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-73',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-73',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-67-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua y Alcantarillado de Tezontepec de Aldama, Hgo. (CAYATAH)',
                'poblacion_atend' => 5398,
                'fecha_apert' => '2003-10-18',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-74',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-74',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-68-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Dirección de Agua Potable',
                'poblacion_atend' => 1731,
                'fecha_apert' => '2004-10-01',
                'fecha_forta' => '2025-12-17',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-75',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-75',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-69-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua y Alcantarillado del municipio de Tizayuca, Hgo. (CAAMTH)',
                'poblacion_atend' => 168302,
                'fecha_apert' => '2003-12-01',
                'fecha_forta' => '2023-12-27',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-76',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-76',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-70-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Y Saneamiento del Municipio de Tlahuelilpan (CASMTH)',
                'poblacion_atend' => 8657,
                'fecha_apert' => '2001-09-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-77',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-77',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-71-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Municipio de Tlahuiltepa',
                'poblacion_atend' => 286,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-78',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-78',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-72-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Municipio de Tlanalapa',
                'poblacion_atend' => 8062,
                'fecha_apert' => '2003-10-01',
                'fecha_forta' => '2025-12-19',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-79',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-79',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-73-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Tlanchinol ECA',
                'poblacion_atend' => 6117,
                'fecha_apert' => '2002-10-14',
                'fecha_forta' => '2025-12-17',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-80',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-80',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-74-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua y Saneamiento del municipio de Tlaxcoapan (CAyST)',
                'poblacion_atend' => 14689,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-81',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-81',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-75-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Presidencia Municipal de Tolcayuca',
                'poblacion_atend' => 8966,
                'fecha_apert' => '2003-12-19',
                'fecha_forta' => '2025-12-18',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-82',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-82',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-76-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable y Alcantarillado de Tula (CAPYAT)',
                'poblacion_atend' => 29390,
                'fecha_apert' => '2001-11-23',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-83',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-83',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-77-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua y Alcantarillado del municipio de Tulancingo (CAAMT)',
                'poblacion_atend' => 105163,
                'fecha_apert' => '2003-10-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-84',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-84',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-77-1-3',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comité Técnico de Aguas Subterráneas del Acuífero del Valle de Tulancingo (COTAS)',
                'poblacion_atend' => 105163,
                'fecha_apert' => '2006-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-86',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-86',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-77-1-5',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Municipio de Tulancingo de Bravo',
                'poblacion_atend' => 105163,
                'fecha_apert' => '2017-11-10',
                'fecha_forta' => '2023-12-27',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-85',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-85',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-78-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Xochiatipan ECA',
                'poblacion_atend' => 1593,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2025-12-18',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-87',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-87',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-79-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Xochicoatlán ECA, Dirección de ecología',
                'poblacion_atend' => 1301,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-88',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-88',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-80-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Yahualica ECA',
                'poblacion_atend' => 24674,
                'fecha_apert' => '2001-12-01',
                'fecha_forta' => '2025-12-18',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-89',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-89',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-81-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Direccion de Obras Publicas y Agua Potable del municipio de Zacualtipan',
                'poblacion_atend' => 29472,
                'fecha_apert' => '2003-11-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-90',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-90',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-82-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Zapotlán ECA',
                'poblacion_atend' => 4978,
                'fecha_apert' => '2004-12-13',
                'fecha_forta' => '2025-12-18',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-91',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-91',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-83-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Zempoala ECA',
                'poblacion_atend' => 7205,
                'fecha_apert' => '2004-12-01',
                'fecha_forta' => '2025-12-18',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-92',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-92',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-83-1-2',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Acueducto Padre Tembleque',
                'poblacion_atend' => 7205,
                'fecha_apert' => '2011-08-10',
                'fecha_forta' => '2025-12-11',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-93',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-93',
                'fecha_registro' => '2026-07-22',
            ],
            [
                'clave_eca' => '13-84-1-1',
                'nombre_inst' => 'Comisión Estatal del Agua y Alcantarillado de Hidalgo',
                'nombre_inst_ope' => 'Comisión de Agua Potable, Alcantarillado y Saneamiento del municipio de Zimapán (CAPASAZIM)',
                'poblacion_atend' => 14732,
                'fecha_apert' => '2002-11-01',
                'fecha_forta' => '2024-09-23',
                'fecha_cierre' => null,
                'motivo_cierre' => 'No Aplica',
                'ruta_logo' => '',
                'id_usuario' => 'USER-94',
                'id_estatus' => 'EST-1K2LMP4X',
                'id_direccion' => 'DIR-94',
                'fecha_registro' => '2026-07-22',
            ],
        ]);
    }
}
