<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsuariosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('usuarios')->insert([
            [
                'id_usuario' => 'USER-1',
                'nombre' => 'Alberto Islas Lópe',
                'correo' => 'agua.potable@acatlanhidalgo.gob.mx',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-06',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-2',
                'nombre' => 'C.Citlali Ortíz Esteban',
                'correo' => 'ECA.presidencia.acaxochitlan@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-07',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-3',
                'nombre' => 'Lic.José Adrián Chávez Cruz',
                'correo' => 'enlaceh2o.actopan@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-08',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-4',
                'nombre' => 'Raúl Santos Muñoz',
                'correo' => 'aguapotable@aguablanca.gob.mx',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-09',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-5',
                'nombre' => 'Lic. Sandra Ethel Arciniega López',
                'correo' => 'culturadelagua.ajacuba@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-10',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-6',
                'nombre' => 'Ing. Jimena Zamudio Sanchez',
                'correo' => 'caamah.culturadelagua24@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-11',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-7',
                'nombre' => 'L.A. Jahtziri Campos Lozada',
                'correo' => 'comisiondeaguaalmoloya24.27@gimail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-12',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-8',
                'nombre' => 'TLC. Brenda Alavarado Alemán',
                'correo' => 'caapan@live.com.mx',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-13',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-9',
                'nombre' => 'TEC. Abigail Eparza Hernández',
                'correo' => 'elarenalaguayalcantarillado@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-14',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-10',
                'nombre' => 'C. Rosa Delia Olguín Prado',
                'correo' => 'culturadelagua.capasmah@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-15',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-11',
                'nombre' => 'C. Hilario Hernández Bautista',
                'correo' => 'mpioatlapexcoaguapotable@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-16',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-12',
                'nombre' => 'Jaquelin Romero Mendoza',
                'correo' => 'comisiondeagua@atotonilcoelgrande.gob.mx',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-17',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-13',
                'nombre' => 'C. Mayra Ivette Solano Romero',
                'correo' => 'cultura.caasat@outlook.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-18',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-14',
                'nombre' => 'Lic. Rossana Salas Alardin',
                'correo' => 'culturadelaguacalnali2021@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-19',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-15',
                'nombre' => 'Moisés Cardón Martínez',
                'correo' => 'culturadelaguamohai@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-20',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-16',
                'nombre' => 'Cynthia Becerril Enciso',
                'correo' => 'capaschh@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-21',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-17',
                'nombre' => 'Jennifer Nava Ángeles',
                'correo' => 'sapchapantongo@hotmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-22',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-18',
                'nombre' => 'Wendy Lima Nuñez',
                'correo' => 'serviciospublicoschapulhuacan@hotmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-23',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-19',
                'nombre' => 'C. Sergio Pérez Serrano',
                'correo' => 'chil20.24serviciosmunicipales@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-24',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-20',
                'nombre' => 'Ing. Iris Piedad García Santamaria',
                'correo' => 'garciastam26@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-25',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-21',
                'nombre' => 'Lic. Alfonso Gustavo Lozano Raya',
                'correo' => 'gus_tavo230705@hotmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-26',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-22',
                'nombre' => 'Leonel Cruz Ortíz',
                'correo' => 'cvsl.2024epazoyucan@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-27',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-23',
                'nombre' => 'C. Maribel Moreno Pérez',
                'correo' => 'morenomaribel516@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-28',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-24',
                'nombre' => 'Lic. Nubya Jazmín Gálvez Ordóñez',
                'correo' => 'eca.organismo.caasvam@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-29',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-25',
                'nombre' => 'Lidia Escorza Gómez',
                'correo' => 'ca.huasca2021@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-30',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-26',
                'nombre' => 'Tec. Avi Melec Contreras Torres',
                'correo' => 'caashuautla@hotmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-31',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-27',
                'nombre' => 'Patricia Hernández Hernández',
                'correo' => 'municipiohuazalingo@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-01',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-28',
                'nombre' => 'Ing. Valente Sevilla Maximino',
                'correo' => 'presidenciahuehuetlahgo2024@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-02',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-29',
                'nombre' => 'Ing. Naiby Arely Sanchez González',
                'correo' => 'culturadelagua7@hotmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-03',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-30',
                'nombre' => 'Mtro. Jesús Manuel Bautista Mateos',
                'correo' => 'culturadelagua@uphuejutla.edu.mx',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-04',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-31',
                'nombre' => 'Gabriela Berrospe Téllez',
                'correo' => 'culturagua@caposa.gob.mx',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-05',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-32',
                'nombre' => 'Ing. Marcos Luis Leon',
                'correo' => 'cotas_htn@hotmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-06',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-33',
                'nombre' => 'L.C.C. Susana Miranda Bernal',
                'correo' => 'culturadelagua@capasmih.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-07',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-34',
                'nombre' => 'Andrea Esmeralda Martínez Abreo',
                'correo' => 'capasjculturadelagua@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-08',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-35',
                'nombre' => 'Emmanuel Montaño Monterrubio',
                'correo' => 'emmanuelmontanomonterrubio@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-09',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-36',
                'nombre' => 'Lisareli López Aragón',
                'correo' => 'espaciodeculturadelaguajh@hotmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-06',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-37',
                'nombre' => 'C. Edgar Mendoza Hernández',
                'correo' => 'reglamentos22@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-11',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-38',
                'nombre' => 'Lic. Saúl Mérida Chávez',
                'correo' => 'asba.miguel@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-12',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-39',
                'nombre' => 'Ing. Juvenal Gutiérrez Balderrama',
                'correo' => 'culturadelagua.sametzquititlan@gmai.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-13',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-40',
                'nombre' => 'Beatriz Monter Melo',
                'correo' => 'presidencia@meztitlan.gob.mx',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-14',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-41',
                'nombre' => 'C. Jesus Lazcano Arriaga',
                'correo' => 'obraspubl_mchico20@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-15',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-42',
                'nombre' => 'Nora Martínez Orozco',
                'correo' => 'at.ecologia2024rm@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-16',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-43',
                'nombre' => 'Norma Leticia Rubio Rubio',
                'correo' => 'presidenciamunicipal@lamision.gob.mx',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-17',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-44',
                'nombre' => 'T.S.U. Ana Mayela Calva Hernández',
                'correo' => 'eca.orgmixquiahuala@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-18',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-45',
                'nombre' => 'Maria Juliana Velazco Reyes',
                'correo' => 'molangoobras2024@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-19',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-46',
                'nombre' => 'C. José Manuel Simón Moreno',
                'correo' => 'obras_20nf24@outlook.es',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-20',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-47',
                'nombre' => 'Ana Patricia Salvador Zúñiga',
                'correo' => 'ecanopala21@hotmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-21',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-48',
                'nombre' => 'Maria de los Ángeles Guerrero Mejía',
                'correo' => 'culturadelagua.omitlan24@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-22',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-49',
                'nombre' => 'Deysi María Castillo Rivera',
                'correo' => 'agua@orizatlan.gob.mx',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-23',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-50',
                'nombre' => 'Ing. Luis Eduardo Hernández Gómez',
                'correo' => 'paculacapasap@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-24',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-51',
                'nombre' => 'Lic. Yadira Garcia Franco',
                'correo' => 'caasim@hidalgo.com.mx',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-25',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-52',
                'nombre' => 'Lic. Luis Garcia Contreras',
                'correo' => 'luis.garciacon@conagua.gob.mx',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-26',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-53',
                'nombre' => 'L.N.I. Martha Beatriz Mejía Hernández',
                'correo' => 'ceaaculturahgo@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-27',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-54',
                'nombre' => 'Mtro. Javier Rosas López',
                'correo' => 'departamentodeeduacionambienta@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-28',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-55',
                'nombre' => 'C. Rogelio Flores Morales',
                'correo' => 'servicospublicos20.24@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-29',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-56',
                'nombre' => 'C. Judith Pérez Trejo',
                'correo' => 'bring1704@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-30',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-57',
                'nombre' => 'Ing. Lucia Guerrero Guerra',
                'correo' => 'culturadelagua.mraldelareforma@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-08-31',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-58',
                'nombre' => 'José Manuel Hernández López',
                'correo' => 'delaguacultura638@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-01',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-59',
                'nombre' => 'José Antonio Trejo Pérez',
                'correo' => 'ceasbth@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-02',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-60',
                'nombre' => 'Lic. Marina Cruz Rivero',
                'correo' => 'sculturadelagua@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-03',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-61',
                'nombre' => 'Ing. Rosa María Vázquez Pérez',
                'correo' => 'culturaagua2427@outlook.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-04',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-62',
                'nombre' => 'Ing. Karina Hernández Gómez',
                'correo' => 'ecacapassa24@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-05',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-63',
                'nombre' => 'Salma Aileth Islas Torres',
                'correo' => 'santiagoculturadelagua@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-06',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-64',
                'nombre' => 'Ing. Elfego Tonatiu Flores Castañeda',
                'correo' => 'ecosinguilucan2427@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-07',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-65',
                'nombre' => 'Fidelia González González',
                'correo' => 'tasquilloaguapotable@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-08',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-66',
                'nombre' => 'Lic. Fernanda Guadalupe De la Cruz Rojo',
                'correo' => 'eca.caast.tecozautla@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-09',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-67',
                'nombre' => 'Ángel de Jesús Sevilla Caro',
                'correo' => 'servimpal2021@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-06',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-68',
                'nombre' => 'Ing. Saúl Cuellar Cordero',
                'correo' => 'aguapotable@tepeapulco.gob.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-11',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-69',
                'nombre' => 'Lic. Ricardo Bautista Resendiz',
                'correo' => 'culturadelaguatepehuacan24@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-12',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-70',
                'nombre' => 'Luis Armando Jiménez',
                'correo' => 'culturadelagua@caamtroh.gob.mx',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-13',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-71',
                'nombre' => 'Pablo Reyes Cerón',
                'correo' => 'tepetitlan.aguapotable@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-14',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-72',
                'nombre' => 'Yazareth Lopez Sanchez',
                'correo' => 'd.aguapotable.2024@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-15',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-73',
                'nombre' => 'Lic. Alejandra Orozco González',
                'correo' => 'ale.ebra1306@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-16',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-74',
                'nombre' => 'C. Martha López Chávez',
                'correo' => 'cayatah.eca@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-17',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-75',
                'nombre' => 'Dorys M. Alonso C.',
                'correo' => 'serviciostianguistengo@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-18',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-76',
                'nombre' => 'C. Analilia Chávez Jauregui',
                'correo' => 'caamth_culturadelagua@outlook.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-19',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-77',
                'nombre' => 'Ing. Daniela Monserrat Hernández Reyes',
                'correo' => 'culturadeaguatlahuelilpan@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-20',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-78',
                'nombre' => 'C. Filimón Solís Vazquez',
                'correo' => 'aguaalcantarilladotlahuiltepa@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-21',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-79',
                'nombre' => 'Ing. Juan Carlos Ávila Olvera',
                'correo' => 'aguapotable@tlanalapa.gob.mx',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-22',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-80',
                'nombre' => 'Xavier Guerrero Cordero',
                'correo' => 'vitemendozajoseluis@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-23',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-81',
                'nombre' => 'Yanet Ángeles Juárez',
                'correo' => 'culturadeagua.tlaxcoapan@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-24',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-82',
                'nombre' => 'Maricruz Bautista Zamora',
                'correo' => 'aguapotable.tolcayuca@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-25',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-83',
                'nombre' => 'Ing. Kennia Islas Escamilla',
                'correo' => 'madonna_lozano@hotmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-26',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-84',
                'nombre' => 'María de los Ángeles Peña Gómez',
                'correo' => 'tulancingo.organismo.eca@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-06',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-85',
                'nombre' => 'Fabiola Vera Hernández',
                'correo' => 'fabi120899@hotmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-28',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-86',
                'nombre' => 'Arq. Sonia Ortiz Camacho',
                'correo' => 'cotastulancingo@hotmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-29',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-87',
                'nombre' => 'Luz Fabiola Gutierrez',
                'correo' => 'hernandezgmario02@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-09-30',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-88',
                'nombre' => 'Alan Noe Pérez López',
                'correo' => 'ecologiarecursos2024@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-10-01',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-89',
                'nombre' => 'Arturo Cortés Hernández',
                'correo' => 'culturadelaguayahualica@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-10-02',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-90',
                'nombre' => 'ING. Arisaid Flores Gómez',
                'correo' => 'desarrollourbano20242027@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-10-03',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-91',
                'nombre' => 'Salvador Bolaños Pitón',
                'correo' => 'ecologiazapotlan2021@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-06',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-92',
                'nombre' => 'C. Sergio Vera Franco',
                'correo' => 'saguapotable2024@hotmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-10-05',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-93',
                'nombre' => 'Dra. Guillermina María Guadalupe Acosta Barrera',
                'correo' => 'zempoala7@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-10-06',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-94',
                'nombre' => 'Ing. Jesus Everardo Guerrero',
                'correo' => 'guerreroeverardo113@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-10-07',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
            [
                'id_usuario' => 'USER-95',
                'nombre' => 'C. Mariana Fernanda Acuña Tejeda',
                'correo' => 'marianaferandaacuñatejeda@gmail.com',
                'correoExtra' => '',
                'password' => Hash::make('RNECA2026'),
                'cambiar_password' => 1,
                'fecha_registro' => '2026-07-06',
                'id_rol' => 'rol1',
                'nombre_jefe' => '',
            ],
        ]);
    }
}
